# Generated by Django 3.2.9 on 2021-12-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=4, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Odólna nazwa przedmiotu zamówienia w ujęciu rodzajowym')),
                ('usedSum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wykorzystano')),
                ('leftSum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wykorzystano')),
                ('cpv', models.ManyToManyField(to='cpvdict.Typecpv')),
            ],
            options={
                'verbose_name': 'Przedmiot zamówienia',
                'verbose_name_plural': 'Klasyfikacja rodzajowa',
            },
        ),
    ]
