# Generated by Django 3.2.9 on 2022-01-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='cpv',
            field=models.ManyToManyField(related_name='Genre', to='cpvdict.Typecpv', verbose_name='Kody CPV'),
        ),
    ]
