# Generated by Django 4.0.5 on 2022-07-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
