# Generated by Django 3.2.9 on 2022-01-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0002_alter_genre_cpv'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='remain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pozostało'),
        ),
    ]
