# Generated by Django 3.2.9 on 2021-12-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0002_orderingobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingobject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ogólna nazwa przedmiotu zamówienia w ujęciu rodzajowym'),
        ),
    ]
