# Generated by Django 4.0.5 on 2022-06-23 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('cpvdict', '0002_order_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data dodania'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.employer', verbose_name='Pracownik'),
            preserve_default=False,
        ),
    ]
