# Generated by Django 4.0.5 on 2022-06-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accessmodule_contractors_module_edit_and_more'),
        ('cpvdict', '0003_order_create_date_order_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.employer', verbose_name='Branżysta'),
        ),
    ]
