# Generated by Django 3.2.9 on 2022-01-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0003_genre_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Suma zamówień'),
        ),
    ]
