# Generated by Django 4.0.5 on 2022-07-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0004_alter_order_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, unique=True, verbose_name='Szacowana kwota'),
        ),
    ]
