# Generated by Django 3.2.9 on 2022-01-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0004_genre_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cpvdict.genre', verbose_name='ID rodzajowości'),
        ),
    ]
