# Generated by Django 4.0.5 on 2022-07-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0004_alter_orderlimit_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlimit',
            options={'ordering': ['year'], 'verbose_name': 'Limit zamówień', 'verbose_name_plural': 'Limit zamówień'},
        ),
    ]
