# Generated by Django 4.0.5 on 2022-07-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0005_alter_orderlimit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlimit',
            options={'ordering': ['-year'], 'verbose_name': 'Limit zamówień', 'verbose_name_plural': 'Limit zamówień'},
        ),
    ]
