# Generated by Django 3.2.9 on 2021-12-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0005_auto_20211220_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingobject',
            name='cpv',
            field=models.ManyToManyField(related_name='OrderingObject', to='cpvdict.Typecpv', verbose_name='Kody CPV'),
        ),
    ]
