# Generated by Django 4.0.5 on 2022-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0005_alter_order_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no_order',
            field=models.CharField(max_length=15, unique=True, verbose_name='Nr zlecenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Szacowana kwota'),
        ),
    ]
