# Generated by Django 3.2.9 on 2021-12-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0006_alter_orderingobject_cpv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderingobject',
            options={'ordering': ['name_id'], 'verbose_name': 'Przedmiot zamówienia', 'verbose_name_plural': 'Klasyfikacja rodzajowa'},
        ),
    ]
