# Generated by Django 4.0.5 on 2022-07-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0006_alter_order_no_order_alter_order_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no_order',
            field=models.CharField(blank=True, default='', max_length=15, unique=True, verbose_name='Nr zlecenia'),
        ),
    ]
