# Generated by Django 4.0.5 on 2022-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0007_alter_order_no_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlimit',
            name='year',
            field=models.IntegerField(default=2022, verbose_name='Rok'),
            preserve_default=False,
        ),
    ]
