# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0007_remove_order_unit_order_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name_id'], 'verbose_name': 'Przedmiot zamówienia', 'verbose_name_plural': 'R.02 - Klasyfikacja rodzajowa'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Zamówienie', 'verbose_name_plural': 'R.05 - Zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='orderlimit',
            options={'ordering': ['-year'], 'verbose_name': 'Limit zamówień', 'verbose_name_plural': 'R.01 - Limit zamówień'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Podatek Vat', 'verbose_name_plural': 'R.04 - Rodzaje podatków vat'},
        ),
        migrations.AlterModelOptions(
            name='typecpv',
            options={'verbose_name': 'CPV', 'verbose_name_plural': 'R.06 - Słownik CPV'},
        ),
        migrations.AlterModelOptions(
            name='typeorder',
            options={'verbose_name': 'Rodzaj zamowienia', 'verbose_name_plural': 'R.03 - Rodzaj zamówienia'},
        ),
    ]
