# Generated by Django 3.2.9 on 2021-12-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0007_alter_orderingobject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('no_order', models.CharField(max_length=15, verbose_name='Nr zlecenia')),
            ],
            options={
                'verbose_name': 'Zlecenie/Umowa',
                'verbose_name_plural': 'Zlecenia/Umowy',
            },
        ),
        migrations.RenameField(
            model_name='typecpv',
            old_name='nocpv',
            new_name='no_cpv',
        ),
    ]
