# Generated by Django 3.2.9 on 2021-12-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_powiat_swop_id'),
        ('cpvdict', '0008_auto_20211229_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True, verbose_name='Rodzaj zamówienia')),
            ],
            options={
                'verbose_name': 'Rodzaj zamowienia',
                'verbose_name_plural': 'Rodzaj zamówienia',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='brakedown',
            field=models.BooleanField(default=1, verbose_name='Awaria'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Szacowana kwota'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='units.unit', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='cpvdict.typeorder', verbose_name='Rodzaj zamówienia'),
            preserve_default=False,
        ),
    ]
