# Generated by Django 4.0.5 on 2022-07-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0008_orderlimit_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlimit',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limit zamówień netto'),
        ),
    ]
