# Generated by Django 4.0.5 on 2022-07-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0009_alter_orderlimit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlimit',
            name='limit',
        ),
        migrations.AddField(
            model_name='orderlimit',
            name='euro_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='Kurs euro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlimit',
            name='limit_brutto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Limit zamowień brutto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlimit',
            name='limit_euro',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Limit euro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlimit',
            name='limit_netto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Limit zamówień netto'),
            preserve_default=False,
        ),
    ]
