# Generated by Django 3.2.9 on 2021-12-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0009_auto_20211229_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderingObject',
            new_name='Genre',
        ),
        migrations.AddField(
            model_name='order',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Zakres'),
        ),
        migrations.AddField(
            model_name='order',
            name='cpv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='cpvdict.genre'),
            preserve_default=False,
        ),
    ]
