# Generated by Django 4.0.5 on 2022-07-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0010_remove_orderlimit_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.SmallIntegerField(default=0, verbose_name='Podatek')),
            ],
            options={
                'verbose_name': 'Podatek Vat',
                'verbose_name_plural': 'Rodzaje podatków vat',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.AddField(
            model_name='order',
            name='sum_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kwota netto'),
        ),
    ]
