# Generated by Django 3.2.9 on 2021-12-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0011_order_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brakedown',
            field=models.BooleanField(default=0, verbose_name='Awaria'),
        ),
    ]
