# Generated by Django 4.0.5 on 2022-07-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0012_alter_tax_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cpvdict.tax', verbose_name='Podatek'),
            preserve_default=False,
        ),
    ]
