# Generated by Django 3.2.9 on 2021-12-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0012_alter_order_brakedown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brakedown',
            field=models.BooleanField(verbose_name='Awaria'),
        ),
    ]
