# Generated by Django 4.0.5 on 2022-07-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0013_order_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum_brutto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota brutto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_netto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Kwota netto'),
        ),
    ]
