# Generated by Django 4.0.5 on 2022-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0014_alter_order_sum_brutto_alter_order_sum_netto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto'),
        ),
    ]
