# Generated by Django 3.2.9 on 2021-12-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0015_auto_20211230_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cpv_id',
            new_name='genre',
        ),
    ]
