# Generated by Django 3.2.9 on 2021-12-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0016_rename_cpv_id_order_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date'], 'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
