# Generated by Django 3.2.9 on 2021-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpvdict', '0017_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limit zamówień')),
            ],
            options={
                'verbose_name': 'Limit zamówień',
                'verbose_name_plural': 'Limit zamówień',
            },
        ),
    ]
