# Generated by Django 4.1 on 2023-01-25 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0020_alter_county_options_alter_county_id_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merits_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Rodzaj merytoryczny',
                'verbose_name_plural': 'Rodzaje merytoryczne',
            },
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Rodzaj zgłoszenia',
                'verbose_name_plural': 'Rodzaje zgłoszeń',
            },
        ),
        migrations.CreateModel(
            name='NeedsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(null=True, verbose_name='Data wpływu')),
                ('case_sign', models.CharField(max_length=30, null=True, verbose_name='Znak pisma')),
                ('case_description', models.TextField(verbose_name='Opis sprawy')),
                ('no_secretariats_diary', models.IntegerField(verbose_name='Nr. z dziennika')),
                ('receipt_date_to_team', models.DateField(verbose_name='Data wpływu do Zespołu')),
                ('case_sign_team', models.CharField(max_length=30, verbose_name='Znak sprawy WiiR')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koszt realizacji')),
                ('isDone', models.BooleanField(verbose_name='Zrealizowane')),
                ('information', models.TextField(verbose_name='Informacje')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needsletter', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('registration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needsletter', to='operationalneedsrecords.registrationtype', verbose_name='Rodzaj zgłoszenia')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needsletter', to='units.unit', verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Ewidencja pism',
                'verbose_name_plural': 'Ewidencje Pism',
            },
        ),
    ]
