# Generated by Django 4.1 on 2023-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='no_secretariats_diary',
            field=models.PositiveIntegerField(unique=True, verbose_name='Nr. z dziennika'),
        ),
    ]
