# Generated by Django 4.1 on 2023-01-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsletter',
            name='case_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='needsletter', to='operationalneedsrecords.meritstype', verbose_name='Rodzaj sprawy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needsletter',
            name='execution_date',
            field=models.DateField(null=True, verbose_name='Data realizacji'),
        ),
    ]
