# Generated by Django 4.1 on 2023-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0002_alter_needsletter_no_secretariats_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='no_secretariats_diary',
            field=models.PositiveIntegerField(verbose_name='Nr. z dziennika'),
        ),
    ]
