# Generated by Django 4.1 on 2023-01-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0002_needsletter_case_type_needsletter_execution_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeritsType',
            new_name='MetricsCaseType',
        ),
    ]
