# Generated by Django 4.1 on 2023-03-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0003_alter_needsletter_no_secretariats_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='no_secretariats_diary',
            field=models.PositiveIntegerField(unique_for_year='receipt_date', verbose_name='Nr. z dziennika'),
        ),
    ]
