# Generated by Django 4.1 on 2023-01-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0003_rename_meritstype_metricscasetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricscasetype',
            options={'ordering': ['merits_type'], 'verbose_name': 'Kategoria sprawy', 'verbose_name_plural': 'Kategorie spraw'},
        ),
        migrations.AlterModelOptions(
            name='registrationtype',
            options={'ordering': ['registration_type'], 'verbose_name': 'Rodzaj zgłoszenia', 'verbose_name_plural': 'Rodzaje zgłoszeń'},
        ),
        migrations.AlterField(
            model_name='metricscasetype',
            name='merits_type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationtype',
            name='registration_type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
