# Generated by Django 4.1 on 2023-01-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_accessmodule_records_letters_and_more'),
        ('operationalneedsrecords', '0004_alter_metricscasetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsletter',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='needsletter', to='main.employer', verbose_name='Branżysta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='needsletter',
            name='no_secretariats_diary',
            field=models.IntegerField(unique=True, verbose_name='Nr. z dziennika'),
        ),
    ]
