# Generated by Django 4.1 on 2023-01-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0005_needsletter_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='case_sign_team',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Znak sprawy WiiR'),
        ),
        migrations.AlterField(
            model_name='needsletter',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt realizacji'),
        ),
        migrations.AlterField(
            model_name='needsletter',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data realizacji'),
        ),
        migrations.AlterField(
            model_name='needsletter',
            name='information',
            field=models.TextField(blank=True, verbose_name='Informacje'),
        ),
        migrations.AlterField(
            model_name='needsletter',
            name='receipt_date_to_team',
            field=models.DateField(blank=True, verbose_name='Data wpływu do Zespołu'),
        ),
    ]
