# Generated by Django 4.1 on 2023-01-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0006_alter_needsletter_case_sign_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricscasetype',
            options={'ordering': ['metric_type'], 'verbose_name': 'Kategoria sprawy', 'verbose_name_plural': 'Kategorie spraw'},
        ),
        migrations.RenameField(
            model_name='metricscasetype',
            old_name='merits_type',
            new_name='metric_type',
        ),
    ]
