# Generated by Django 4.1 on 2023-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0008_alter_metricscasetype_metric_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needsletter',
            options={'ordering': ['-receipt_date'], 'verbose_name': 'Ewidencja pism', 'verbose_name_plural': 'Ewidencje Pism'},
        ),
        migrations.AlterField(
            model_name='needsletter',
            name='case_sign',
            field=models.CharField(max_length=50, null=True, verbose_name='Znak pisma'),
        ),
    ]
