# Generated by Django 4.1 on 2023-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0009_alter_needsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='execution_date',
            field=models.DateField(null=True, verbose_name='Data realizacji'),
        ),
    ]
