# Generated by Django 4.1 on 2023-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0010_alter_needsletter_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data realizacji'),
        ),
    ]
