# Generated by Django 4.1 on 2023-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0011_alter_needsletter_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='isDone',
            field=models.BooleanField(default=False, verbose_name='Zrealizowane'),
        ),
    ]
