# Generated by Django 4.1 on 2023-02-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0013_alter_metricscasetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Koszt realizacji'),
        ),
    ]
