# Generated by Django 4.1 on 2023-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationalneedsrecords', '0016_alter_needsletter_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsletter',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt realizacji'),
        ),
    ]
