# Generated by Django 3.2.9 on 2021-12-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Paragrafy', 'verbose_name_plural': 'Paragraf'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Rozdziały', 'verbose_name_plural': 'Rozdział'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Źródła', 'verbose_name_plural': 'Źródło'},
        ),
    ]
