# Generated by Django 3.2.9 on 2022-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Rozdział', 'verbose_name_plural': 'Rozdziały'},
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph',
            field=models.CharField(max_length=7, verbose_name='Paragraf'),
        ),
    ]
