# Generated by Django 4.1 on 2022-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section'], 'verbose_name': 'Rozdział', 'verbose_name_plural': 'Rozdziały'},
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=5, unique=True, verbose_name='Rozdział'),
        ),
    ]
