# Generated by Django 3.2.9 on 2022-01-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0002_auto_20220103_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Źródło finansowania', 'verbose_name_plural': 'Źródła finansowania'},
        ),
    ]
