# Generated by Django 3.2.9 on 2021-12-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0002_auto_20211206_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=2, verbose_name='Grupa')),
            ],
            options={
                'verbose_name': 'Grupy',
                'verbose_name_plural': 'Grupa',
            },
        ),
        migrations.AddField(
            model_name='financesource',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcefinancing.group', verbose_name='Grupa'),
            preserve_default=False,
        ),
    ]
