# Generated by Django 4.1 on 2022-10-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0002_alter_section_options_alter_section_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(max_length=2, unique=True, verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph',
            field=models.CharField(max_length=7, unique=True, verbose_name='Paragraf'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Źródło'),
        ),
    ]
