# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0003_alter_group_group_alter_paragraph_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financesource',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'K.05 - Konta'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'K.01 - Grupy'},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Paragraf i pozycja', 'verbose_name_plural': 'K.03 - Paragrafy i pozycje'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section'], 'verbose_name': 'Rozdział', 'verbose_name_plural': 'K.02 - Rozdziały'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Źródło finansowania', 'verbose_name_plural': 'K.04 - Źródła finansowania'},
        ),
    ]
