# Generated by Django 3.2.9 on 2021-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0003_auto_20211206_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nazwa'),
            preserve_default=False,
        ),
    ]
