# Generated by Django 3.2.9 on 2021-12-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0004_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financesource',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'Konta'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'Grupy'},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Paragraf i pozycja', 'verbose_name_plural': 'Paragrafy i pozycje'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Rozdział', 'verbose_name_plural': 'Rozdziay'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Źródło', 'verbose_name_plural': 'Źródła'},
        ),
    ]
