# Generated by Django 3.2.9 on 2022-05-05 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contractauction_worker'),
        ('units', '0002_auto_20220414_2018'),
        ('sourcefinancing', '0001_initial'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_of_acceptance'], 'verbose_name': 'Zadanie inwestycyjne', 'verbose_name_plural': 'Zadania inwestycyjne'},
        ),
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='contracts.contractauction', verbose_name='Umowa'),
        ),
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_of_acceptance',
            field=models.DateField(blank=True, null=True, verbose_name='Data pisma'),
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='sourcefinancing.group', verbose_name='Grupa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje'),
        ),
        migrations.AddField(
            model_name='project',
            name='investment_cost_estimate_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='WKI'),
        ),
        migrations.AddField(
            model_name='project',
            name='investment_program',
            field=models.FileField(blank=True, null=True, upload_to='investment_program/%Y/', verbose_name='Program inwestycji'),
        ),
        migrations.AddField(
            model_name='project',
            name='no_acceptance_document',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Liczba pisma'),
        ),
        migrations.AddField(
            model_name='project',
            name='paragraph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='sourcefinancing.paragraph', verbose_name='Paragraf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa zadania'),
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='sourcefinancing.section', verbose_name='Rozdział'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source_financing',
            field=models.TextField(blank=True, null=True, verbose_name='Opis źródła finansowania'),
        ),
        migrations.AddField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='units.unit', verbose_name='Jednostka'),
            preserve_default=False,
        ),
    ]
