# Generated by Django 3.2.9 on 2022-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Pełna nazwa zadania'),
        ),
    ]
