# Generated by Django 3.2.9 on 2022-05-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20220505_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contract',
        ),
    ]
