# Generated by Django 4.0.5 on 2022-07-21 19:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_project_source_financing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='information',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Informacje'),
        ),
    ]
