# Generated by Django 3.2.9 on 2022-06-07 09:04

from django.db import migrations, models
import investments.models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_project_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='investment_program',
            field=models.FileField(blank=True, null=True, upload_to=investments.models.upload_scan, verbose_name='Program inwestycji'),
        ),
        migrations.AlterField(
            model_name='project',
            name='settlement_scan',
            field=models.FileField(blank=True, null=True, upload_to=investments.models.upload_scan, verbose_name='Rozliczenie inwestycyjne'),
        ),
    ]
