# Generated by Django 3.2.9 on 2022-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_auto_20220607_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='investment_program',
            field=models.FileField(blank=True, null=True, upload_to='investments', verbose_name='Program inwestycji'),
        ),
    ]
