# Generated by Django 4.1 on 2022-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_project_source_financing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pełna nazwa zadania'),
        ),
    ]
