# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_project_project_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_of_acceptance'], 'verbose_name': 'Zadanie inwestycyjne', 'verbose_name_plural': 'I.01 - Zadania inwestycyjne'},
        ),
    ]
