# Generated by Django 3.2.9 on 2022-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='change',
            field=models.DateField(auto_now=True, verbose_name='Zmiana'),
        ),
    ]
