# Generated by Django 4.0.5 on 2022-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_alter_project_investment_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='change',
            field=models.DateTimeField(auto_now=True, verbose_name='Zmiana'),
        ),
    ]
