# Generated by Django 3.2.9 on 2022-05-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_command_scan'),
        ('investments', '0007_project_realized'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='main.employer', verbose_name='Odpowiedzialny'),
            preserve_default=False,
        ),
    ]
