# Generated by Django 4.0.5 on 2022-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_accessmodule_employers_accessmodule_teams'),
        ('investments', '0007_alter_project_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='worker',
            field=models.ManyToManyField(related_name='project', to='main.employer', verbose_name='Inspektor'),
        ),
    ]
