# Generated by Django 3.2.9 on 2022-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_auto_20220526_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_of_acceptance',
            field=models.DateField(blank=True, null=True, verbose_name='Data programu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pełna nazwa zadania'),
        ),
    ]
