# Generated by Django 3.2.9 on 2022-05-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_command_scan'),
        ('investments', '0014_auto_20220526_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='worker',
            field=models.ManyToManyField(related_name='project', to='main.Employer', verbose_name='Branżysta'),
        ),
    ]
