# Generated by Django 3.2.9 on 2021-12-08 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0008_auto_20211207_1050'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0002_alter_contractorsell_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Wystawcy faktur',
                'verbose_name_plural': 'Pracownik',
            },
        ),
        migrations.CreateModel(
            name='Invoicesell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data wystawienia')),
                ('noinvoice', models.CharField(max_length=11, verbose_name='Nr. faktury')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Kwota')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Informacje')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiana')),
                ('autor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contractimmovables', verbose_name='Umowa')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractorsell', verbose_name='Kontrahent')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.creator', verbose_name='Osoba wystawiająca')),
            ],
            options={
                'verbose_name': 'Faktury',
                'verbose_name_plural': 'Faktura',
            },
        ),
    ]
