# Generated by Django 3.2.9 on 2022-04-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='powiat',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='invoicesell',
            old_name='powiat',
            new_name='county',
        ),
    ]
