# Generated by Django 4.1 on 2023-09-13 09:23

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='period_from',
            field=models.CharField(max_length=7, validators=[invoices.models.validate_period], verbose_name='Okres od'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_to',
            field=models.CharField(max_length=7, validators=[invoices.models.validate_period], verbose_name='Okres do'),
        ),
    ]
