# Generated by Django 4.0.5 on 2022-07-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employer_invoices_issues'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to='main.employer', verbose_name='Osoba wystawiająca'),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
