# Generated by Django 3.2.9 on 2021-12-14 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0003_rename_contractorsell_contractor'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicebuy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invoiceitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota [zł]')),
                ('powiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitems', to='units.powiat', verbose_name='Powiat')),
            ],
        ),
        migrations.CreateModel(
            name='Invoicebuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datawyplytu', models.DateField(verbose_name='Data wypływu')),
                ('data', models.DateField(verbose_name='Data wystawienia')),
                ('noinvoice', models.CharField(max_length=30, verbose_name='Nr. faktury')),
                ('period_from', models.DateField(verbose_name='Okres od')),
                ('period_to', models.DateField(verbose_name='Okres do')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Informacje')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiana')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicebuy', to='contractors.contractor', verbose_name='Kontrahent')),
                ('invoiceitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitems', to='invoices.invoiceitems', verbose_name='Składowe faktury')),
            ],
            options={
                'verbose_name': 'Faktura - kupno',
                'verbose_name_plural': 'Faktury - kupno',
            },
        ),
    ]
