# Generated by Django 3.2.9 on 2022-06-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicebuy',
            options={'ordering': ['-date_receipt'], 'verbose_name': 'Faktura - kupno', 'verbose_name_plural': 'Faktury - kupno'},
        ),
        migrations.AlterModelOptions(
            name='invoicesell',
            options={'ordering': ['-date'], 'verbose_name': 'Faktura sprzedaży', 'verbose_name_plural': 'Faktury - sprzedaż'},
        ),
    ]
