# Generated by Django 3.2.9 on 2022-04-13 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicebuy',
            old_name='change',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='invoicebuy',
            old_name='create',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='invoicebuy',
            old_name='data',
            new_name='date_issue',
        ),
        migrations.RenameField(
            model_name='invoicebuy',
            old_name='comments',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='invoicebuy',
            old_name='invoiceitems',
            new_name='invoice_items',
        ),
        migrations.RenameField(
            model_name='invoicebuy',
            old_name='noinvoice',
            new_name='no_invoice',
        ),
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='acount',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='invoicesell',
            old_name='change',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='invoicesell',
            old_name='create',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='invoicesell',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='invoicesell',
            old_name='comments',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='invoicesell',
            old_name='noinvoice',
            new_name='no_invoice',
        ),
        migrations.RemoveField(
            model_name='invoicebuy',
            name='datawyplytu',
        ),
        migrations.AddField(
            model_name='invoicebuy',
            name='date_receipt',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wpływu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicebuy',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota [zł]'),
        ),
        migrations.AlterField(
            model_name='invoicebuy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicebuy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to=settings.AUTH_USER_MODEL),
        ),
    ]
