# Generated by Django 3.2.9 on 2021-12-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'Pracownikr', 'verbose_name_plural': 'Wystawcy faktur - sprzedaż'},
        ),
        migrations.AlterModelOptions(
            name='invoicesell',
            options={'verbose_name': 'Faktura sprzedaży', 'verbose_name_plural': 'Faktury - sprzedaż'},
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota'),
        ),
    ]
