# Generated by Django 3.2.9 on 2021-12-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_auto_20211208_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'Pracownik', 'verbose_name_plural': 'Wystawcy faktur - sprzedaż'},
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
