# Generated by Django 3.2.9 on 2022-04-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20220427_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='author',
        ),
    ]
