# Generated by Django 3.2.9 on 2021-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20211214_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebuy',
            name='invoiceitems',
        ),
        migrations.AddField(
            model_name='invoicebuy',
            name='invoiceitems',
            field=models.ManyToManyField(related_name='invoiceitems', to='invoices.Invoiceitems'),
        ),
    ]
