# Generated by Django 4.1 on 2022-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoicesell_creator_delete_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctivenote',
            name='corrective_invoice',
            field=models.CharField(max_length=70, verbose_name='Korygowana faktura'),
        ),
    ]
