# Generated by Django 3.2.9 on 2022-06-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20220609_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebuy',
            name='period_from',
        ),
        migrations.RemoveField(
            model_name='invoicebuy',
            name='period_to',
        ),
    ]
