# Generated by Django 4.1 on 2023-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoicesell_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='period_from',
            field=models.CharField(max_length=7, verbose_name='Okres od'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_to',
            field=models.CharField(max_length=7, verbose_name='Okres do'),
        ),
    ]
