# Generated by Django 3.2.9 on 2021-12-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_creator_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicesell',
            old_name='autor',
            new_name='uzytkownik',
        ),
    ]
