# Generated by Django 3.2.9 on 2022-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20220620_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Typ dokumentu')),
            ],
        ),
    ]
