# Generated by Django 4.1 on 2022-08-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0016_alter_unit_information'),
        ('sourcefinancing', '0001_initial'),
        ('invoices', '0003_alter_correctivenote_corrective_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sourcefinancing.financesource', verbose_name='Konto'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='units.county', verbose_name='Powiat'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoicebuy', verbose_name='ID Faktury'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto [zł]'),
        ),
    ]
