# Generated by Django 3.2.9 on 2021-12-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcefinancing', '0001_initial'),
        ('invoices', '0003_auto_20211214_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='acount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitems', to='sourcefinancing.financesource', verbose_name='Konto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='invoicebuy',
            name='invoiceitems',
        ),
        migrations.AddField(
            model_name='invoicebuy',
            name='invoiceitems',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitems', to='invoices.invoiceitems', verbose_name='Źródło finansowania'),
            preserve_default=False,
        ),
    ]
