# Generated by Django 3.2.9 on 2021-12-07 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0003_rename_autor_invoicesell_uzytkownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='uzytkownik',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
