# Generated by Django 3.2.9 on 2022-05-27 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_creator_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebuy',
            name='date_of_payment',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Termin płatności'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesell',
            name='date_of_payment',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Termin płatności'),
            preserve_default=False,
        ),
    ]
