# Generated by Django 4.1 on 2023-09-12 17:17

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoicesell_period_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='period_from',
            field=month.models.MonthField(verbose_name='Okres od'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_to',
            field=month.models.MonthField(verbose_name='Okres do'),
        ),
    ]
