# Generated by Django 3.2.9 on 2021-12-08 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20211208_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesell',
            name='period_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Za okres od'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesell',
            name='period_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Za okres do'),
            preserve_default=False,
        ),
    ]
