# Generated by Django 3.2.9 on 2022-06-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_documenttypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'verbose_name': 'Rodzaj dokumentu księgowego', 'verbose_name_plural': 'Rodzaje dokumentów księgowych'},
        ),
    ]
