# Generated by Django 3.2.9 on 2021-12-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20211215_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'verbose_name': 'Element faktury', 'verbose_name_plural': 'Elementy faktury'},
        ),
    ]
