# Generated by Django 4.1 on 2022-08-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitems_account_alter_invoiceitems_county_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'ordering': ['invoice_id'], 'verbose_name': 'Element faktury', 'verbose_name_plural': 'Elementy faktury'},
        ),
    ]
