# Generated by Django 3.2.9 on 2021-12-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_alter_unit_aktywna'),
        ('invoices', '0004_auto_20211208_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesell',
            name='contract',
        ),
        migrations.AddField(
            model_name='invoicesell',
            name='powiat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='units.powiat', verbose_name='Powiat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_from',
            field=models.DateField(verbose_name='Okres od'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_to',
            field=models.DateField(verbose_name='Okres do'),
        ),
    ]
