# Generated by Django 4.1 on 2023-09-12 17:55

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoicesell_period_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='period_from',
            field=models.DateField(validators=[invoices.models.validate_period], verbose_name='Okres od'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_to',
            field=models.DateField(validators=[invoices.models.validate_period], verbose_name='Okres do'),
        ),
    ]
