# Generated by Django 3.2.9 on 2021-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoiceitems_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='creator',
            field=models.CharField(max_length=20, verbose_name='Pracownik'),
        ),
    ]
