# Generated by Django 4.1 on 2022-10-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoiceitems_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoicebuy', verbose_name='Faktura'),
        ),
    ]
