# Generated by Django 3.2.9 on 2021-12-09 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_alter_unit_aktywna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0005_alter_contractorsell_options'),
        ('invoices', '0005_auto_20211209_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to='contractors.contractorsell', verbose_name='Kontrahent'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to='invoices.creator', verbose_name='Osoba wystawiająca'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='powiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to='units.powiat', verbose_name='Powiat'),
        ),
    ]
