# Generated by Django 3.2.9 on 2022-06-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_documenttypes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebuy',
            name='doc_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoicebuy', to='invoices.documenttypes', verbose_name='Rodzaj dokumentu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesell',
            name='doc_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to='invoices.documenttypes', verbose_name='Rodzaj dokumentu'),
            preserve_default=False,
        ),
    ]
