# Generated by Django 3.2.9 on 2022-06-21 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_alter_contractor_nip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0006_auto_20220620_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data wystawienia')),
                ('no_note', models.CharField(max_length=15, verbose_name='Nr. noty')),
                ('corrective_invoice', models.CharField(max_length=30, verbose_name='Korygowana faktura')),
                ('information', models.TextField(blank=True, default='', verbose_name='Informacje')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctivenote', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctivenote', to='contractors.contractor', verbose_name='Kontrahent')),
            ],
            options={
                'verbose_name': 'Nota korygująca',
                'verbose_name_plural': 'Noty korygujące',
            },
        ),
    ]
