# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoiceitems_invoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctivenote',
            options={'ordering': ['-date'], 'verbose_name': 'Nota korygująca', 'verbose_name_plural': 'F.02 - Noty korygujące'},
        ),
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'verbose_name': 'Rodzaj dokumentu księgowego', 'verbose_name_plural': 'F.05 - Rodzaje dokumentów księgowych'},
        ),
        migrations.AlterModelOptions(
            name='invoicebuy',
            options={'ordering': ['-date_receipt'], 'verbose_name': 'Faktura - kupno', 'verbose_name_plural': 'F.03 - Faktury - kupno'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'ordering': ['invoice_id'], 'verbose_name': 'Element faktury', 'verbose_name_plural': 'F.04 - Elementy faktury'},
        ),
        migrations.AlterModelOptions(
            name='invoicesell',
            options={'ordering': ['-date'], 'verbose_name': 'Faktura sprzedaży', 'verbose_name_plural': 'F.01 - Faktury - sprzedaż'},
        ),
    ]
