# Generated by Django 3.2.9 on 2021-12-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_budgetyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetYear',
        ),
    ]
