# Generated by Django 3.2.9 on 2022-06-21 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_correctivenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctivenote',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data uworzenia'),
            preserve_default=False,
        ),
    ]
