# Generated by Django 3.2.9 on 2021-12-29 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0008_delete_budgetyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicebuy',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='invoicesell',
            old_name='autor',
            new_name='author',
        ),
        migrations.AddField(
            model_name='creator',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auth.user'),
            preserve_default=False,
        ),
    ]
