# Generated by Django 4.1 on 2023-02-16 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0008_alter_invoicesell_period_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicesell', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_from',
            field=models.DateField(verbose_name='Okres od'),
        ),
        migrations.AlterField(
            model_name='invoicesell',
            name='period_to',
            field=models.DateField(verbose_name='Okres do'),
        ),
    ]
