# Generated by Django 3.2.9 on 2022-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_correctivenote_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctivenote',
            options={'ordering': ['-date'], 'verbose_name': 'Nota korygująca', 'verbose_name_plural': 'Noty korygujące'},
        ),
        migrations.AlterField(
            model_name='correctivenote',
            name='no_note',
            field=models.CharField(max_length=30, verbose_name='Nr. noty'),
        ),
    ]
