# Generated by Django 3.2.9 on 2021-12-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20211229_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesell',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota [zł]'),
        ),
    ]
