# Generated by Django 3.2.9 on 2022-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20220621_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctivenote',
            name='corrective_invoice',
            field=models.CharField(max_length=50, verbose_name='Korygowana faktura'),
        ),
        migrations.AlterField(
            model_name='correctivenote',
            name='no_note',
            field=models.CharField(max_length=15, verbose_name='Nr. noty'),
        ),
    ]
