# Generated by Django 4.0.5 on 2022-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20220621_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctivenote',
            name='information',
            field=models.TextField(blank=True, default='', verbose_name='Korygowana treść'),
        ),
    ]
