# Generated by Django 4.1 on 2023-02-17 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(verbose_name='Nazwa galerii')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='investments.project', verbose_name='Projekt INW')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'G.02 - Galerie',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(max_length=300, upload_to=gallery.models.upload_gallery, verbose_name='Zdjęcie')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='gallery.gallery', verbose_name='Galeria')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'G.01 - Zdjęcia',
                'ordering': ['add_date'],
            },
        ),
    ]
