# Generated by Django 3.2.9 on 2022-06-06 13:53

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_delete_gallery'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.DateField(verbose_name='Nazwa galerii'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='investments.project', verbose_name='Projekt INW'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='gallery.gallery', verbose_name='Galeria'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to=gallery.models.upload_gallery, verbose_name='Zdjęcie'),
        ),
    ]
