# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-name'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'G.02 - Galerie'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['add_date'], 'verbose_name': 'Zdjęcie', 'verbose_name_plural': 'G.01 - Zdjęcia'},
        ),
    ]
