# Generated by Django 3.2.9 on 2022-06-06 14:01

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20220606_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(max_length=300, upload_to=gallery.models.upload_gallery, verbose_name='Zdjęcie'),
        ),
    ]
