# Generated by Django 3.2.9 on 2022-06-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_src'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-name'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerie'},
        ),
    ]
