# Generated by Django 4.1 on 2023-09-13 08:07

import contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0001_initial'),
        ('main', '0001_initial'),
        ('cpvdict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('no_contract', models.CharField(max_length=20, unique=True, verbose_name='Nr. umowy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Wartość umowy')),
                ('work_scope', models.CharField(max_length=120, verbose_name='Przedmiot umowy')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('last_report_date', models.DateField(blank=True, null=True, verbose_name='Data ostatniego protokołu')),
                ('guarantee_period', models.IntegerField(verbose_name='Okres gwarancji')),
                ('warranty_period', models.IntegerField(verbose_name='Okres rękojmi')),
                ('security_percent', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Procent zabezpiecznia')),
                ('security_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota zabezpiecznia')),
                ('report', models.TextField(blank=True, default='', verbose_name='Raportowanie')),
                ('information', models.TextField(blank=True, default='', verbose_name='Informacje')),
                ('scan', models.FileField(blank=True, null=True, upload_to=contracts.models.up_load_contract_auction, verbose_name='Skan umowy')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='contractors.contractor', verbose_name='Kontrahent')),
            ],
            options={
                'verbose_name': 'Umowa ZZP',
                'verbose_name_plural': 'U.09 - Umowy ZZP',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ContractMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data umowy')),
                ('no_contract', models.CharField(max_length=30, verbose_name='Nr.umowy')),
                ('content', models.CharField(max_length=100, verbose_name='Treść')),
                ('period_of_validity', models.DateField(blank=True, null=True, verbose_name='Data obowiązywania')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wartośc umowy')),
                ('information', models.TextField(blank=True, default='', verbose_name='Informacje')),
                ('scan', models.FileField(blank=True, null=True, upload_to=contracts.models.upload_contract_media, verbose_name='Skan')),
                ('state', models.BooleanField(default=True, verbose_name='Aktualna')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_media', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_media', to='contractors.contractor', verbose_name='Wykonawca')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_media', to='main.employer', verbose_name='Branżysta')),
            ],
            options={
                'verbose_name': 'Umowa na Media',
                'verbose_name_plural': 'U.04 - Umowy Media',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee', models.CharField(max_length=50, verbose_name='Gwarancja')),
            ],
            options={
                'verbose_name': 'Gwarancja',
                'verbose_name_plural': 'U.12 - Umowy ZZP - Rodzaje Gwarancji',
                'ordering': ['guarantee'],
            },
        ),
        migrations.CreateModel(
            name='LegalBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=100, verbose_name='Ustawa')),
                ('legal_basic', models.CharField(max_length=30, verbose_name='Paragraf w ustawie')),
                ('legal_basic_text', models.TextField(verbose_name='Tekst paragrafu')),
            ],
            options={
                'verbose_name': 'Podstawa prawna',
                'verbose_name_plural': 'U.13 - Podstawy prawne',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='Media')),
                ('folders_type', models.CharField(max_length=30, verbose_name='Nazwa folderu')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'U.06 - Umowy Media - Rodzaje Mediów',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Rodzaj umowy',
                'verbose_name_plural': 'U.03 - Umowy Nieruchomości - Rodzaje umów',
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measureName', models.CharField(max_length=30, verbose_name='Jednostka miary')),
            ],
            options={
                'verbose_name': 'Jednostka miary',
                'verbose_name_plural': 'U.08 - Jednostki miary',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GuaranteeSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_settlement', models.DateField(verbose_name='Termin zwrotu')),
                ('settlement_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kwota zwrotu')),
                ('script', models.CharField(max_length=50, verbose_name='L.dz. Pisma')),
                ('affirmation_settlement', models.BooleanField(default=False, verbose_name='Rozliczono')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_settlement', to='contracts.contractauction', verbose_name='Umowa')),
            ],
            options={
                'verbose_name': 'Rozliczenie umowy',
                'verbose_name_plural': 'U.11 - Umowy ZZP - Rozliczenia umów: Gwarancje',
                'ordering': ['deadline_settlement'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('no_document', models.CharField(max_length=30, verbose_name='Nr. dokumentu')),
                ('value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Zużycie')),
                ('cost_netto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota netto')),
                ('cost_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto')),
                ('information', models.TextField(blank=True, default='', null=True, verbose_name='Informacje')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialdocument', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialdocument', to='contracts.contractmedia', verbose_name='Uowa')),
                ('unit_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialdocument', to='contracts.unitmeasure', verbose_name='Jednostka miary')),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialdocument', to='cpvdict.tax', verbose_name='Vat')),
            ],
            options={
                'verbose_name': 'Dokument księgowy',
                'verbose_name_plural': 'U.07 - Dokumenty księkowe',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='contractmedia',
            name='legal_basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_media', to='contracts.legalbasic', verbose_name='Tryb UPZP'),
        ),
        migrations.AddField(
            model_name='contractmedia',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractmedia', to='contracts.mediatype', verbose_name='Rodzaj umowy'),
        ),
        migrations.AddField(
            model_name='contractmedia',
            name='unit',
            field=models.ManyToManyField(related_name='contract_media', to='units.unit', verbose_name='Jednostka'),
        ),
        migrations.CreateModel(
            name='ContractImmovables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('no_contract', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Nr umowy')),
                ('period_of_validity', models.DateField(blank=True, null=True, verbose_name='Okres obowiązywania')),
                ('usable_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Powierzchnia użytkowa')),
                ('rent_cost', models.BooleanField(verbose_name='Czynsz')),
                ('electric_cost', models.BooleanField(verbose_name='Prąd')),
                ('gas_cost', models.BooleanField(verbose_name='Gaz')),
                ('water_cost', models.BooleanField(verbose_name='Woda')),
                ('central_heating_cost', models.BooleanField(verbose_name='C.O.')),
                ('garbage_cost', models.BooleanField(verbose_name='Śmieci')),
                ('garbage_tax_cost', models.BooleanField(verbose_name='Zagospodarowanie odpadami komunalnymi')),
                ('property_cost', models.BooleanField(verbose_name='Podatek od nieruchomości')),
                ('scan', models.FileField(blank=True, null=True, upload_to=contracts.models.upload_scan_contract_immovables, verbose_name='Skan umowy')),
                ('state', models.BooleanField(default=True, verbose_name='Aktualna')),
                ('information', models.TextField(blank=True, default='', verbose_name='Informacje')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contractors.contractor', verbose_name='Kontrahent')),
                ('legal_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contracts.legalbasic', verbose_name='Podstawa prawna')),
                ('type_of_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contracts.typeofcontract', verbose_name='Rodzaj umowy')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='units.unit', verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Umowa nieruchomosci',
                'verbose_name_plural': 'U.01 - Umowy Nieruchomości',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='contractauction',
            name='guarantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='contracts.guarantee', verbose_name='Gwarancja'),
        ),
        migrations.AddField(
            model_name='contractauction',
            name='investments_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='investments.project', verbose_name='Zadanie inwestycyjne'),
        ),
        migrations.AddField(
            model_name='contractauction',
            name='legal_basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='contracts.legalbasic', verbose_name='Tryb UPZP'),
        ),
        migrations.AddField(
            model_name='contractauction',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='units.unit', verbose_name='Jednostka'),
        ),
        migrations.AddField(
            model_name='contractauction',
            name='worker',
            field=models.ManyToManyField(related_name='contract_auction', to='main.employer', verbose_name='Inspektor'),
        ),
        migrations.CreateModel(
            name='AnnexImmovables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_annex', models.FileField(null=True, upload_to=contracts.models.upload_scan_annex_contract_immovables, verbose_name='Skan aneks')),
                ('date_annex', models.DateField(null=True, verbose_name='Data aneksu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract_immovables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex', to='contracts.contractimmovables', verbose_name='umowa')),
            ],
            options={
                'verbose_name': 'Aneks na umowę nieruchomości',
                'verbose_name_plural': 'U.02 - Umowy Nieruchomości - Aneksy',
                'ordering': ['contract_immovables', 'date_annex'],
            },
        ),
        migrations.CreateModel(
            name='AnnexContractMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data aneksu')),
                ('scope_changes', models.TextField(blank=True, default='', verbose_name='Zakres zmian')),
                ('scan', models.FileField(blank=True, null=True, upload_to=contracts.models.upload_annex_contract_media, verbose_name='Skan aneksu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex_contract_media', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contract_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex_contract_media', to='contracts.contractmedia', verbose_name='Umowa')),
            ],
            options={
                'verbose_name': 'Aneks Umowy na media',
                'verbose_name_plural': 'U.05 - Umowy Media - Aneksy',
                'ordering': ['contract_media', 'date'],
            },
        ),
        migrations.CreateModel(
            name='AnnexContractAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data aneksu')),
                ('price_change', models.BooleanField(default=False, verbose_name='Zmiana wartości umowy')),
                ('price_after_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota aneksu')),
                ('scope_changes', models.TextField(blank=True, default='', verbose_name='Zakres zmian')),
                ('scan', models.FileField(blank=True, null=True, upload_to=contracts.models.up_load_annex_contract_auction, verbose_name='Skan aneksu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexcontractauction', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contract_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aneks_contract_auction', to='contracts.contractauction', verbose_name='Umowa ZZP')),
            ],
            options={
                'verbose_name': 'Aneks na umowę ZZP',
                'verbose_name_plural': 'U.10 - Umowy ZZP - Aneksy',
                'ordering': ['contract_auction', 'date'],
            },
        ),
    ]
