# Generated by Django 3.2.9 on 2021-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractimmovables',
            name='inf_co',
        ),
        migrations.RemoveField(
            model_name='contractimmovables',
            name='inf_gaz',
        ),
        migrations.RemoveField(
            model_name='contractimmovables',
            name='inf_prad',
        ),
        migrations.RemoveField(
            model_name='contractimmovables',
            name='inf_woda',
        ),
        migrations.AddField(
            model_name='contractimmovables',
            name='koszt_czynsz',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractimmovables',
            name='koszt_smieci',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
