# Generated by Django 3.2.9 on 2022-01-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aneksimmovables',
            old_name='contract',
            new_name='contractimmovables',
        ),
    ]
