# Generated by Django 4.0.5 on 2022-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data umowy')),
            ],
            options={
                'verbose_name': 'Umowa na media',
                'verbose_name_plural': 'Umowy na media',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='Media')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Rodzaje Mediów',
            },
        ),
    ]
