# Generated by Django 3.2.9 on 2022-04-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalbasic',
            options={'verbose_name': 'Podstawa prawna', 'verbose_name_plural': 'Podstawy prawne'},
        ),
        migrations.RemoveField(
            model_name='contractauction',
            name='legal_basic_zzp',
        ),
        migrations.AddField(
            model_name='contractauction',
            name='legal_basic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='contracts.legalbasic', verbose_name='Tryb UPZP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalbasic',
            name='act',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalbasic',
            name='legal_basic_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LegalBasicZzp',
        ),
    ]
