# Generated by Django 3.2.9 on 2022-06-07 11:12

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneximmovables',
            name='scan_annex',
            field=models.FileField(null=True, upload_to=contracts.models.upload_scan_contract_immovables, verbose_name='Skan aneks'),
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='no_contract',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nr. umowy'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.upload_scan_contract_immovables, verbose_name='Skan umowy'),
        ),
    ]
