# Generated by Django 3.2.9 on 2021-12-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='skan',
            field=models.FileField(blank=True, null=True, upload_to='umowy_pdf/%Y/', verbose_name='Skan umowy'),
        ),
    ]
