# Generated by Django 3.2.9 on 2022-04-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220414_2018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_auto_20220418_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='inspector',
            field=models.ManyToManyField(related_name='ContractAuction', to='main.Employer', verbose_name='Inspektor'),
        ),
    ]
