# Generated by Django 3.2.9 on 2021-12-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contractimmovables_skan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aneks',
            name='umowa_id',
        ),
        migrations.AddField(
            model_name='aneks',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aneks', to='contracts.contractimmovables'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aneks',
            name='skan_aneksu',
            field=models.FileField(blank=True, null=True, upload_to='aneksy_pdf/%Y/', verbose_name='Skan aneksu'),
        ),
    ]
