# Generated by Django 3.2.9 on 2022-01-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_contract_aneksimmovables_contractimmovables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='autor',
            new_name='author',
        ),
    ]
