# Generated by Django 3.2.9 on 2021-12-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_rename_jednostka_unit'),
        ('contracts', '0002_contract_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
    ]
