# Generated by Django 3.2.9 on 2022-06-10 10:24

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20220607_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneximmovables',
            name='scan_annex',
            field=models.FileField(null=True, upload_to=contracts.models.upload_scan_annex_contract_immovables, verbose_name='Skan aneks'),
        ),
    ]
