# Generated by Django 4.0.5 on 2022-07-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_anneximmovables_scan_annex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='security_percent',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Procent zabezpiecznia'),
        ),
    ]
