# Generated by Django 4.0.5 on 2022-07-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractmedia_author_contractmedia_change_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatype',
            options={'ordering': ['type'], 'verbose_name': 'Media', 'verbose_name_plural': 'Rodzaje Mediów'},
        ),
    ]
