# Generated by Django 3.2.9 on 2021-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20211214_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aneks',
            options={'verbose_name': 'Aneks', 'verbose_name_plural': 'Aneksy'},
        ),
        migrations.AlterField(
            model_name='aneks',
            name='skan_aneksu',
            field=models.FileField(blank=True, null=True, upload_to='aneksy_pdf/%Y/', verbose_name='Skan aneks'),
        ),
    ]
