# Generated by Django 3.2.9 on 2021-12-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Umowa', 'verbose_name_plural': 'Umowy'},
        ),
    ]
