# Generated by Django 3.2.9 on 2022-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20220418_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractauction',
            old_name='inspector',
            new_name='worker',
        ),
    ]
