# Generated by Django 3.2.9 on 2021-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contractimmovables_archives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='koszt_co',
            field=models.BooleanField(verbose_name='C.O.'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='koszt_czynsz',
            field=models.BooleanField(verbose_name='Czynsz'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='koszt_gaz',
            field=models.BooleanField(verbose_name='Gaz'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='koszt_prad',
            field=models.BooleanField(verbose_name='Prąd'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='koszt_smieci',
            field=models.BooleanField(verbose_name='Śmieci'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='koszt_woda',
            field=models.BooleanField(verbose_name='Woda'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='nrumowy',
            field=models.CharField(blank=True, default='BRAK', max_length=20, verbose_name='Nr umowy'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='pow_uzyczona',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Powierzchnia użytkowa'),
        ),
    ]
