# Generated by Django 3.2.9 on 2021-12-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20211214_2035'),
        ('contractors', '0004_auto_20211215_1329'),
        ('contracts', '0004_auto_20211214_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aneks',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aneks', to='contracts.contractimmovables', verbose_name='Umowa'),
        ),
        migrations.AlterField(
            model_name='aneks',
            name='skan_aneksu',
            field=models.FileField(blank=True, null=True, upload_to='contracts_immovables_pdf/aneksy_pdf/%Y/', verbose_name='Skan aneks'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='kontrahent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contractors.contractor', verbose_name='Kontrahent'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='podstawa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contracts.podstawa', verbose_name='Podstawa prawna'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contracts.rodzaj', verbose_name='Rodzaj umowy'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='skan',
            field=models.FileField(blank=True, null=True, upload_to='contracts_immovables_pdf/%Y/', verbose_name='Skan umowy'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='stan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contracts.stan'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='units.unit', verbose_name='Jednostka'),
        ),
    ]
