# Generated by Django 3.2.9 on 2021-12-03 23:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_auto_20211203_1340'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0006_rename_jednostka_unit'),
        ('contracts', '0004_alter_contract_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Contractimmovables',
        ),
    ]
