# Generated by Django 3.2.9 on 2021-12-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_alter_unit_options'),
        ('contracts', '0004_auto_20211206_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractimmovables',
            name='powiat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='units.powiat', verbose_name='Powiat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit', verbose_name='Jednostka'),
        ),
    ]
