# Generated by Django 3.2.9 on 2021-12-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_rename_contract_contractimmovables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractimmovables',
            options={'verbose_name': 'Umowa nieruchomosci', 'verbose_name_plural': 'Umowy nieruchomosci'},
        ),
    ]
