# Generated by Django 3.2.9 on 2022-04-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20220418_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractimmovables',
            name='archives',
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contracts.state', verbose_name='Stan'),
        ),
    ]
