# Generated by Django 3.2.9 on 2021-12-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20211206_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractimmovables',
            name='powiat',
        ),
    ]
