# Generated by Django 4.0.5 on 2022-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractmedia_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmedia',
            name='period_of_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Data obowiązywania'),
        ),
    ]
