# Generated by Django 3.2.9 on 2022-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20220426_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneximmovables',
            name='date_annex',
            field=models.DateField(null=True, verbose_name='Data aneksu'),
        ),
    ]
