# Generated by Django 3.2.9 on 2021-12-07 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0006_remove_contractimmovables_powiat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Informacje'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='kontrahent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractorsell', verbose_name='Kontrahent'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='podstawa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.podstawa', verbose_name='Podstawa prawna'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.rodzaj', verbose_name='Rodzaj umowy'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='skan',
            field=models.FileField(blank=True, null=True, upload_to='umowy_pdf', verbose_name='Skan umowy'),
        ),
        migrations.CreateModel(
            name='Aneks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skan_aneksu', models.FileField(blank=True, null=True, upload_to='aneksy_pdf/%Y', verbose_name='Skan aneksu')),
                ('data_aneksu', models.DateField(null=True, verbose_name='Data aneksu')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('umowa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contractimmovables')),
            ],
        ),
    ]
