# Generated by Django 3.2.9 on 2022-04-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_anneximmovables_date_annex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneximmovables',
            name='date_annex',
            field=models.DateField(blank=True, null=True, verbose_name='Data aneksu'),
        ),
    ]
