# Generated by Django 4.0.5 on 2022-07-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractmedia_period_of_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementContractAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_part_security_date', models.DateField(verbose_name='Termin')),
                ('first_part_security_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Zabezpieczenie 70%')),
                ('first_part_security_writing', models.CharField(max_length=50, verbose_name='Zabezpieczenie 70%')),
                ('first_part_security_checkbox', models.BooleanField(verbose_name='Oddano 70%')),
                ('second_part_security_date', models.DateField(verbose_name='Termin')),
                ('second_part_security_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Zabezpieczenie 30%')),
                ('second_part_security_writing', models.CharField(max_length=50, verbose_name='Zabezpieczenie 30%')),
                ('second_part_security_checkbox', models.BooleanField(verbose_name='Oddano 30%')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlementcontractauction', to='contracts.contractauction', verbose_name='Umowa')),
            ],
        ),
    ]
