# Generated by Django 3.2.9 on 2021-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20211207_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractimmovables',
            name='koszt_podnier',
            field=models.BooleanField(default=1, verbose_name='Podatek od nieruchomości'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractimmovables',
            name='koszt_podsmiec',
            field=models.BooleanField(default=1, verbose_name='Zagospodarowanie odpadami komunalnymi'),
            preserve_default=False,
        ),
    ]
