# Generated by Django 3.2.9 on 2022-01-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20220110_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aneksimmovables',
            options={'ordering': ['contractimmovables', 'data_aneksu'], 'verbose_name': 'Aneks', 'verbose_name_plural': 'Nieruchomosci - Aneksy'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Okres', 'verbose_name_plural': 'Umowy ZZP - Okresy'},
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='data_umowy',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
