# Generated by Django 4.0.5 on 2022-08-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_settlementcontractauction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlementcontractauction',
            options={'ordering': ['first_part_security_date', 'second_part_security_date'], 'verbose_name': 'Rozliczenie umowy', 'verbose_name_plural': 'Rozliczenia umów ZZP'},
        ),
        migrations.RenameField(
            model_name='contractmedia',
            old_name='change_date',
            new_name='change',
        ),
    ]
