# Generated by Django 3.2.9 on 2021-12-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20211207_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='pow_uzyczona',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Powierzchnia użytkowa'),
        ),
    ]
