# Generated by Django 3.2.9 on 2022-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_anneximmovables_date_annex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=20, verbose_name='Stan'),
        ),
    ]
