# Generated by Django 3.2.9 on 2021-12-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0009_alter_contractimmovables_pow_uzyczona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
