# Generated by Django 3.2.9 on 2022-04-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_state_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='state',
            field=models.ForeignKey(default='Aktualna', on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to='contracts.state', verbose_name='Stan'),
        ),
    ]
