# Generated by Django 4.0.5 on 2022-08-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_settlementcontractauction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='folders_type',
            field=models.CharField(default=1, max_length=30, verbose_name='Nazwa folderu'),
            preserve_default=False,
        ),
    ]
