# Generated by Django 3.2.9 on 2021-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_contractimmovables_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='archives',
            field=models.BooleanField(default=1, verbose_name='Aktywna'),
        ),
    ]
