# Generated by Django 3.2.9 on 2022-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_contractimmovables_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneximmovables',
            name='date_annex',
            field=models.DateField(null=True, verbose_name='Data aneksu'),
        ),
        migrations.AlterField(
            model_name='anneximmovables',
            name='scan_annex',
            field=models.FileField(null=True, upload_to='contracts_immovables/annexes/%Y/', verbose_name='Skan aneks'),
        ),
    ]
