# Generated by Django 3.2.9 on 2022-01-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inspector_permissionstype'),
        ('contracts', '0010_auto_20220110_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractauction',
            old_name='informations',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='contractauction',
            old_name='raports',
            new_name='raport',
        ),
        migrations.AddField(
            model_name='contractauction',
            name='inspector',
            field=models.ManyToManyField(related_name='ContractAuction', to='main.Inspector', verbose_name='Inspektor'),
        ),
        migrations.AddField(
            model_name='contractauction',
            name='work_scope',
            field=models.CharField(default=1, max_length=120, verbose_name='Zakres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='contracts_zzp/%Y/', verbose_name='Skan umowy'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='skan',
            field=models.FileField(blank=True, null=True, upload_to='contracts_immovables/%Y/', verbose_name='Skan umowy'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.SmallIntegerField(verbose_name='Okres (mc)'),
        ),
    ]
