# Generated by Django 4.0.5 on 2022-08-03 11:32

import contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0010_mediatype_folders_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnexContractMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data aneksu')),
                ('scope_changes', models.TextField(blank=True, default='', verbose_name='Zakres zmian')),
                ('scan', models.FileField(blank=True, null=True, upload_to=contracts.models.up_load_annex_contract_auction, verbose_name='Skan aneksu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexcontractmedia', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('contract_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexcontractmedia', to='contracts.contractmedia', verbose_name='Aneksy Media')),
            ],
            options={
                'verbose_name': 'Aneks Umowy na media',
                'verbose_name_plural': 'Umowy Media - Aneksy',
                'ordering': ['contract_media', 'date'],
            },
        ),
    ]
