# Generated by Django 4.0.5 on 2022-08-03 11:33

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_annexcontractmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexcontractmedia',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.upload_annex_contract_media, verbose_name='Skan aneksu'),
        ),
    ]
