# Generated by Django 3.2.9 on 2022-01-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_auto_20220110_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='guarantee_period',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='warranty_period',
            field=models.TextField(),
        ),
    ]
