# Generated by Django 3.2.9 on 2021-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contractimmovables_archives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='nrumowy',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Nr umowy'),
        ),
    ]
