# Generated by Django 3.2.9 on 2022-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220502_1225'),
        ('contracts', '0011_auto_20220429_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='worker',
            field=models.ManyToManyField(related_name='contract_auction', to='main.Employer', verbose_name='Inspektor'),
        ),
    ]
