# Generated by Django 3.2.9 on 2022-05-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_project_contract'),
        ('contracts', '0012_alter_contractauction_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractauction',
            name='investments_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='investments.project', verbose_name='Zadanie inwestycyjne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anneximmovables',
            name='contract_immovables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex', to='contracts.contractimmovables', verbose_name='umowa'),
        ),
    ]
