# Generated by Django 3.2.9 on 2021-12-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contractimmovables_nrumowy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='nrumowy',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Nr umowy'),
        ),
    ]
