# Generated by Django 3.2.9 on 2022-01-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_period_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuaranteePeriod',
        ),
    ]
