# Generated by Django 3.2.9 on 2022-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_auto_20220506_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Stan'),
        ),
    ]
