# Generated by Django 4.0.5 on 2022-08-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_alter_annexcontractmedia_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmedia',
            name='legal_basic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_media', to='contracts.legalbasic', verbose_name='Tryb UPZP'),
            preserve_default=False,
        ),
    ]
