# Generated by Django 4.0.5 on 2022-08-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0016_contractmedia_legal_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractimmovables', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
