# Generated by Django 3.2.9 on 2022-01-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_guaranteeperiod_warrantyperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='guarantee_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='contracts.guaranteeperiod', verbose_name='Okres gwarancji'),
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='warranty_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='contracts.warrantyperiod', verbose_name='Okres rękojmi'),
        ),
    ]
