# Generated by Django 3.2.9 on 2022-01-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_auto_20220112_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteeperiod',
            name='guarantee_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GuaranteePeriod', to='contracts.period', verbose_name='Okres gwarancji'),
            preserve_default=False,
        ),
    ]
