# Generated by Django 4.1 on 2022-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_contractimmovables_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='guarantee_period',
            field=models.IntegerField(verbose_name='Okres gwarancji'),
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='warranty_period',
            field=models.IntegerField(verbose_name='Okres rękojmi'),
        ),
    ]
