# Generated by Django 3.2.9 on 2022-01-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_guaranteeperiod_guarantee_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyperiod',
            name='warranty_period',
            field=models.SmallIntegerField(default=1, verbose_name='Okres rękojmi (mc)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guaranteeperiod',
            name='guarantee_period',
            field=models.SmallIntegerField(verbose_name='Okres gwarancji (mc)'),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
