# Generated by Django 4.1 on 2022-08-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_alter_contractauction_guarantee_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedline_settlement', models.DateField(verbose_name='Termin zwrotu')),
                ('settlement_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Kwota zwrotu')),
                ('script', models.CharField(max_length=50, verbose_name='L.dz. Pisma')),
                ('affirmation_settlement', models.BooleanField(verbose_name='Rozliczono')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlementcontractauction', to='contracts.contractauction', verbose_name='Umowa')),
            ],
            options={
                'verbose_name': 'Rozliczenie umowy',
                'verbose_name_plural': 'Umowy ZZP - Rozliczenia umów',
                'ordering': ['dedline_settlement'],
            },
        ),
        migrations.DeleteModel(
            name='SettlementContractAuction',
        ),
    ]
