# Generated by Django 3.2.9 on 2022-01-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_auto_20220113_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guaranteeperiod',
            options={'ordering': ['guarantee_period'], 'verbose_name': 'Okres gwarancyjny', 'verbose_name_plural': 'Okresy gwarancyjne'},
        ),
        migrations.AlterModelOptions(
            name='warrantyperiod',
            options={'ordering': ['warranty_period'], 'verbose_name': 'Okres rękojmi', 'verbose_name_plural': 'Okresy rękojmi'},
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='work_scope',
            field=models.CharField(max_length=120, verbose_name='Przedmiot umowy'),
        ),
    ]
