# Generated by Django 3.2.9 on 2022-05-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_alter_contractimmovables_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractauction',
            old_name='change_date',
            new_name='change',
        ),
    ]
