# Generated by Django 3.2.9 on 2022-01-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220113_0735'),
        ('contracts', '0020_auto_20220113_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='inspector',
            field=models.ManyToManyField(blank=True, null=True, related_name='ContractAuction', to='main.Inspector', verbose_name='Inspektor'),
        ),
    ]
