# Generated by Django 3.2.9 on 2022-05-31 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_auto_20220526_1201'),
        ('contracts', '0021_rename_change_date_contractauction_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='investments_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_auction', to='investments.project', verbose_name='Zadanie inwestycyjne'),
        ),
    ]
