# Generated by Django 3.2.9 on 2022-01-13 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_auto_20220113_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zakończenia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractauction',
            name='last_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data ostatniego protokołu'),
        ),
    ]
