# Generated by Django 4.1 on 2022-08-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_alter_contractmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guarantee',
            options={'ordering': ['guarantee'], 'verbose_name': 'Gwarancja', 'verbose_name_plural': 'Umowy ZZP - Rodzaje Gwarancji'},
        ),
        migrations.AlterField(
            model_name='guaranteesettlement',
            name='affirmation_settlement',
            field=models.BooleanField(default=False, verbose_name='Rozliczono'),
        ),
        migrations.AlterField(
            model_name='guaranteesettlement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_settlement', to='contracts.contractauction', verbose_name='Umowa'),
        ),
        migrations.AlterField(
            model_name='guaranteesettlement',
            name='script',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='L.dz. Pisma'),
        ),
        migrations.AlterField(
            model_name='guaranteesettlement',
            name='settlement_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kwota zwrotu'),
        ),
    ]
