# Generated by Django 3.2.9 on 2022-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_alter_contractauction_investments_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexcontractauction',
            name='price_after_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota aneksu'),
        ),
    ]
