# Generated by Django 3.2.9 on 2022-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220113_0735'),
        ('contracts', '0022_auto_20220113_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='inspector',
            field=models.ManyToManyField(related_name='ContractAuction', to='main.Inspector', verbose_name='Inspektor'),
        ),
    ]
