# Generated by Django 3.2.9 on 2022-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_alter_contractauction_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anekscontractauction',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data aneksu'),
        ),
    ]
