# Generated by Django 4.1 on 2022-09-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_alter_contractauction_guarantee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guaranteesettlement',
            options={'ordering': ['deadline_settlement'], 'verbose_name': 'Rozliczenie umowy', 'verbose_name_plural': 'Umowy ZZP - Rozliczenia umów: Gwarancje'},
        ),
        migrations.RenameField(
            model_name='guaranteesettlement',
            old_name='dedline_settlement',
            new_name='deadline_settlement',
        ),
    ]
