# Generated by Django 3.2.9 on 2022-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_alter_annexcontractauction_price_after_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexcontractauction',
            name='date',
            field=models.DateField(verbose_name='Data aneksu'),
        ),
    ]
