# Generated by Django 4.1 on 2023-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_guaranteesettlement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteesettlement',
            name='script',
            field=models.CharField(default=1, max_length=50, verbose_name='L.dz. Pisma'),
            preserve_default=False,
        ),
    ]
