# Generated by Django 3.2.9 on 2022-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_anekscontractauction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aneksimmovables',
            name='data_aneksu',
            field=models.DateField(blank=True, null=True, verbose_name='Data aneksu'),
        ),
    ]
