# Generated by Django 3.2.9 on 2022-01-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_alter_aneksimmovables_skan_aneksu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='pow_uzyczona',
            field=models.DecimalField(blank=True, decimal_places=2, default='0,00', max_digits=8, null=True, verbose_name='Powierzchnia użytkowa'),
        ),
    ]
