# Generated by Django 4.1 on 2023-02-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_alter_unitmeasure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='cost_brutto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto'),
        ),
    ]
