# Generated by Django 3.2.9 on 2022-01-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_alter_contractimmovables_pow_uzyczona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aneksimmovables',
            name='skan_aneksu',
            field=models.FileField(blank=True, null=True, upload_to='contracts_immovables/annexes/%Y/', verbose_name='Skan aneks'),
        ),
        migrations.AlterField(
            model_name='contractimmovables',
            name='pow_uzyczona',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Powierzchnia użytkowa'),
        ),
    ]
