# Generated by Django 3.2.9 on 2022-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_auto_20220121_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractimmovables',
            name='pow_uzyczona',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Powierzchnia użytkowa'),
        ),
    ]
