# Generated by Django 4.1 on 2023-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_alter_financialdocument_cost_brutto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='cost_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota brutto'),
        ),
    ]
