# Generated by Django 3.2.9 on 2022-01-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_alter_contractimmovables_pow_uzyczona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractauction',
            name='contract_security',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota zabezpiecznia'),
        ),
    ]
