# Generated by Django 4.1 on 2023-02-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_alter_financialdocument_cost_brutto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdocument',
            options={'ordering': ['-date'], 'verbose_name': 'Dokument księgowy', 'verbose_name_plural': 'Dokumenty księkowe'},
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Zużycie'),
        ),
    ]
