# Generated by Django 3.2.9 on 2022-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_alter_contractauction_contract_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalbasiczzp',
            name='legal_basic_zzp_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
