# Generated by Django 4.1 on 2023-02-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_alter_annexcontractauction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annexcontractauction',
            options={'ordering': ['contract_auction', 'date'], 'verbose_name': 'Aneks na umowę ZZP', 'verbose_name_plural': 'U.10 - Umowy ZZP - Aneksy'},
        ),
        migrations.AlterModelOptions(
            name='annexcontractmedia',
            options={'ordering': ['contract_media', 'date'], 'verbose_name': 'Aneks Umowy na media', 'verbose_name_plural': 'U.05 - Umowy Media - Aneksy'},
        ),
    ]
