# Generated by Django 3.2.9 on 2022-04-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0031_legalbasiczzp_legal_basic_zzp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnexImmovables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_annex', models.FileField(blank=True, null=True, upload_to='contracts_immovables/annexes/%Y/', verbose_name='Skan aneks')),
                ('date_annex', models.DateField(blank=True, null=True, verbose_name='Data aneksu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aneks',
                'verbose_name_plural': 'Nieruchomosci - Aneksy',
                'ordering': ['contract_immovables', 'date_annex'],
            },
        ),
        migrations.RenameModel(
            old_name='AneksContractAuction',
            new_name='AnnexContractAuction',
        ),
        migrations.RenameModel(
            old_name='Podstawa',
            new_name='LegalBasic',
        ),
        migrations.RenameModel(
            old_name='Stan',
            new_name='State',
        ),
        migrations.RenameModel(
            old_name='Rodzaj',
            new_name='TypeOfContract',
        ),
        migrations.AlterModelOptions(
            name='contractimmovables',
            options={'ordering': ['date'], 'verbose_name': 'Umowa nieruchomosci', 'verbose_name_plural': 'Nieruchomości - Umowy'},
        ),
        migrations.RenameField(
            model_name='annexcontractauction',
            old_name='create',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='contractauction',
            old_name='change',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='contractauction',
            old_name='create',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='contractauction',
            old_name='raport',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='contractauction',
            old_name='contract_security',
            new_name='security_sum',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_co',
            new_name='central_heating_cost',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='kontrahent',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='create',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='data_umowy',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_prad',
            new_name='electric_cost',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_smieci',
            new_name='garbage_cost',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_podsmiec',
            new_name='garbage_tax_cost',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_gaz',
            new_name='gas_cost',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='comments',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='podstawa',
            new_name='legal_basic',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='nrumowy',
            new_name='no_contract',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='okres_obowiazywania',
            new_name='period_of_validity',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_podnier',
            new_name='property_cost',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_czynsz',
            new_name='rent_cost',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='skan',
            new_name='scan',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='stan',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='rodzaj',
            new_name='type_of_contract',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='pow_uzyczona',
            new_name='usable_area',
        ),
        migrations.RenameField(
            model_name='contractimmovables',
            old_name='koszt_woda',
            new_name='water_cost',
        ),
        migrations.RenameField(
            model_name='legalbasic',
            old_name='podstawa',
            new_name='legal_basic',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='stan',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='typeofcontract',
            old_name='rodzaj',
            new_name='type',
        ),
        migrations.DeleteModel(
            name='AneksImmovables',
        ),
        migrations.AddField(
            model_name='anneximmovables',
            name='contract_immovables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex', to='contracts.contractimmovables', verbose_name='Umowa'),
        ),
    ]
