# Generated by Django 4.1 on 2023-02-17 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swop_id', models.CharField(max_length=4, verbose_name='ID SWOP')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Powiat')),
                ('id_order', models.IntegerField(null=True, unique=True, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Powiat',
                'verbose_name_plural': 'J.01 - Powiaty',
                'ordering': ['id_order'],
            },
        ),
        migrations.CreateModel(
            name='TypeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_short', models.CharField(max_length=10, verbose_name='Skrócona nazwa')),
                ('type_full', models.CharField(max_length=30, verbose_name='Pełna nazwa')),
            ],
            options={
                'verbose_name': 'Rodzaj jednostki',
                'verbose_name_plural': 'J.02 - Rodzaje jednostek',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=40, verbose_name='Miasto')),
                ('information', models.CharField(blank=True, max_length=200, verbose_name='Obiekt')),
                ('manager', models.CharField(default='Policja', max_length=150, verbose_name='Trwały zarząd')),
                ('comments', models.TextField(blank=True, verbose_name='Uwagi')),
                ('status', models.BooleanField(default=True, verbose_name='Aktualna')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Pełna nazwa jednostki')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiany')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.county', verbose_name='Powiat')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.typeunit', verbose_name='Rodzaj jednostki')),
            ],
            options={
                'verbose_name': 'Jednostka',
                'verbose_name_plural': 'J.03 - Jednostki',
                'ordering': ['county__name', 'type'],
            },
        ),
    ]
