# Generated by Django 3.2.9 on 2021-12-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Powiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swop_id', models.CharField(max_length=4)),
                ('powiat', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Powiat',
                'verbose_name_plural': 'Powiaty',
            },
        ),
        migrations.CreateModel(
            name='Rodzaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Rodzaj jednostki',
                'verbose_name_plural': 'Rodzaje jednostek',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=30)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('miasto', models.CharField(max_length=20)),
                ('informacje', models.TextField(blank=True)),
                ('aktywna', models.BooleanField(default=0, verbose_name='Aktywna')),
                ('powiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.powiat')),
                ('rodzaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.rodzaj')),
            ],
            options={
                'verbose_name': 'Jednostka',
                'verbose_name_plural': 'Jednostki',
            },
        ),
    ]
