# Generated by Django 3.2.9 on 2021-11-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jednostka',
            old_name='archiwum',
            new_name='aktywna',
        ),
    ]
