# Generated by Django 3.2.9 on 2022-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeunit',
            options={'ordering': ['id'], 'verbose_name': 'Rodzaj jednostki', 'verbose_name_plural': 'Rodzaje jednostek'},
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Powiat'),
        ),
        migrations.AlterField(
            model_name='county',
            name='swop_id',
            field=models.CharField(max_length=4, unique=True, verbose_name='ID SWOP'),
        ),
        migrations.AlterField(
            model_name='typeunit',
            name='type_full',
            field=models.CharField(max_length=30, verbose_name='Pełna nazwa'),
        ),
        migrations.AlterField(
            model_name='typeunit',
            name='type_short',
            field=models.CharField(max_length=10, verbose_name='Skrócona nazwa'),
        ),
    ]
