# Generated by Django 3.2.9 on 2021-12-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='powiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.powiat'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.rodzaj'),
        ),
    ]
