# Generated by Django 4.0.5 on 2022-07-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.county', verbose_name='Powiat'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='information',
            field=models.TextField(blank=True, verbose_name='Informacje'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='manager',
            field=models.CharField(max_length=50, verbose_name='Trwały zarząd'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.typeunit', verbose_name='Rodzaj jednostki'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='zip_code',
            field=models.CharField(max_length=6, verbose_name='Kod pocztowy'),
        ),
    ]
