# Generated by Django 3.2.9 on 2021-12-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20211214_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powiat',
            options={'ordering': ['swop_id'], 'verbose_name': 'Powiat', 'verbose_name_plural': 'Powiaty'},
        ),
    ]
