# Generated by Django 4.0.5 on 2022-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_unit_address_alter_unit_city_alter_unit_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Uwagi'),
        ),
    ]
