# Generated by Django 3.2.9 on 2021-11-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_rename_archiwum_jednostka_aktywna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiat',
            name='powiat',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rodzaj',
            name='rodzaj',
            field=models.CharField(max_length=10),
        ),
    ]
