# Generated by Django 3.2.9 on 2022-05-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20220414_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county'], 'verbose_name': 'Jednostka', 'verbose_name_plural': 'Jednostki'},
        ),
    ]
