# Generated by Django 3.2.9 on 2021-11-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20211128_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiat',
            name='swop_id',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
