# Generated by Django 3.2.9 on 2022-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_unit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='change',
            field=models.DateTimeField(auto_now=True, verbose_name='Zmiany'),
        ),
    ]
