# Generated by Django 3.2.9 on 2021-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_powiat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiat',
            name='swop_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
