# Generated by Django 3.2.9 on 2021-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_powiat_swop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiat',
            name='swop_id',
            field=models.CharField(max_length=4),
        ),
    ]
