# Generated by Django 3.2.9 on 2022-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_powiat_swop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
