# Generated by Django 4.0.5 on 2022-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_unit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='information',
            field=models.TextField(blank=True, verbose_name='Obiekt'),
        ),
    ]
