# Generated by Django 3.2.9 on 2021-12-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_alter_powiat_swop_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jednostka',
            new_name='Unit',
        ),
    ]
