# Generated by Django 4.0.5 on 2022-07-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_alter_unit_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Miasto'),
        ),
    ]
