# Generated by Django 3.2.9 on 2022-03-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_unit_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='adres',
            new_name='address',
        ),
    ]
