# Generated by Django 3.2.9 on 2021-12-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_rename_jednostka_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Jednostki', 'verbose_name_plural': 'Jednostka'},
        ),
    ]
