# Generated by Django 4.0.5 on 2022-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_alter_unit_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='full_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Pełna nazwa jednostki'),
        ),
    ]
