# Generated by Django 3.2.9 on 2022-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_rename_adres_unit_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rodzaj',
            new_name='UnitKind',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='rodzaj',
            new_name='unit_kind',
        ),
        migrations.RenameField(
            model_name='unitkind',
            old_name='rodzaj',
            new_name='unit_kind',
        ),
        migrations.AlterField(
            model_name='unit',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Adres'),
        ),
    ]
