# Generated by Django 3.2.9 on 2022-03-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_auto_20220318_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.unitkind', verbose_name='Rodzaj'),
        ),
    ]
