# Generated by Django 4.0.5 on 2022-08-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_unit_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pełna nazwa jednostki'),
        ),
    ]
