# Generated by Django 3.2.9 on 2021-12-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powiat',
            options={'verbose_name': 'Powiat', 'verbose_name_plural': 'Powiaty'},
        ),
        migrations.AlterModelOptions(
            name='rodzaj',
            options={'verbose_name': 'Rodzaj jednostki', 'verbose_name_plural': 'Rodzaje jednostek'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Jednostka', 'verbose_name_plural': 'Jednostki'},
        ),
    ]
