# Generated by Django 3.2.9 on 2021-12-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_auto_20211208_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='aktywna',
            field=models.BooleanField(default=0, verbose_name='Archiwum'),
        ),
    ]
