# Generated by Django 4.0.5 on 2022-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_alter_unit_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='manager',
            field=models.CharField(default='Policja', max_length=50, verbose_name='Trwały zarząd'),
        ),
    ]
