# Generated by Django 3.2.9 on 2021-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_alter_unit_aktywna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='aktywna',
            field=models.BooleanField(default=0, verbose_name='Aktywna'),
        ),
    ]
