# Generated by Django 4.0.5 on 2022-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0013_alter_unit_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Aktualna'),
        ),
    ]
