# Generated by Django 4.0.5 on 2022-08-08 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0014_alter_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
