# Generated by Django 4.1 on 2022-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0016_alter_unit_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Aktualna"),
        ),
    ]
