# Generated by Django 4.1 on 2022-10-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0017_alter_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Powiat'),
        ),
        migrations.AlterField(
            model_name='county',
            name='swop_id',
            field=models.CharField(max_length=4, verbose_name='ID SWOP'),
        ),
    ]
