# Generated by Django 4.1 on 2022-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0018_alter_county_name_alter_county_swop_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county__name', 'type'], 'verbose_name': 'Jednostka', 'verbose_name_plural': 'Jednostki'},
        ),
        migrations.AddField(
            model_name='county',
            name='id_order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
