# Generated by Django 4.1 on 2022-10-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_alter_unit_options_county_id_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['id_order'], 'verbose_name': 'Powiat', 'verbose_name_plural': 'Powiaty'},
        ),
        migrations.AlterField(
            model_name='county',
            name='id_order',
            field=models.IntegerField(null=True, unique=True, verbose_name='Kolejność'),
        ),
    ]
