# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0020_alter_county_options_alter_county_id_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['id_order'], 'verbose_name': 'Powiat', 'verbose_name_plural': 'J.01 - Powiaty'},
        ),
        migrations.AlterModelOptions(
            name='typeunit',
            options={'ordering': ['id'], 'verbose_name': 'Rodzaj jednostki', 'verbose_name_plural': 'J.02 - Rodzaje jednostek'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['county__name', 'type'], 'verbose_name': 'Jednostka', 'verbose_name_plural': 'J.03 - Jednostki'},
        ),
    ]
