# Generated by Django 4.1 on 2023-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessflats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialflat',
            name='city',
            field=models.CharField(default=1, max_length=40, verbose_name='Miasto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialflat',
            name='zip_code',
            field=models.CharField(default=1, max_length=6, verbose_name='Kod pocztowy'),
            preserve_default=False,
        ),
    ]
