# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessflats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialflat',
            options={'verbose_name': 'Mieszkanie służbowe', 'verbose_name_plural': 'M.01 - Mieszkania służbowe'},
        ),
    ]
