# Generated by Django 4.1 on 2023-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessflats', '0002_officialflat_city_officialflat_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialflat',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
