# Generated by Django 4.0.5 on 2022-06-28 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0009_alter_contractor_no_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40, verbose_name='Rodzaj')),
            ],
            options={
                'verbose_name': 'Rodzaj darowizny',
                'verbose_name_plural': 'Rodzaje darowizn',
            },
        ),
        migrations.CreateModel(
            name='TypeFinancialResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40, verbose_name='Rodzaj środków')),
            ],
            options={
                'verbose_name': 'Rodzaj środków',
                'verbose_name_plural': 'Rodzaje środków',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=25, verbose_name='L.dz.')),
                ('date_receipt', models.DateField(verbose_name='Data wpływu')),
                ('date_return', models.DateField(verbose_name='Data zwrotu od Wydz. Finansów')),
                ('no_application', models.CharField(max_length=10, verbose_name='Nr. wniosku')),
                ('no_agreement', models.CharField(max_length=25, verbose_name='Nr. porozumienia')),
                ('date_agreement', models.DateField(verbose_name='Data porozumienia')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('settlement_date', models.DateField(verbose_name='Data rozliczenia')),
                ('subject', models.TextField(verbose_name='Przedmiot porozumienia')),
                ('engagement', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zaangażowanie')),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wydatek')),
                ('information', models.TextField(verbose_name='Informacje')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('donation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='donations.typedonation', verbose_name='Rodzaj darowizny')),
                ('financial_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='donations.typefinancialresources', verbose_name='Rodzaj środków')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='contractors.contractor', verbose_name='Darczyńca')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='units.unit', verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Wniosek',
                'verbose_name_plural': 'Wnioski',
                'ordering': ['date_receipt'],
            },
        ),
    ]
