# Generated by Django 4.0.5 on 2022-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='change',
            field=models.DateField(auto_now=True),
        ),
    ]
