# Generated by Django 4.0.5 on 2022-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_application_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='engagement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zaangażowanie'),
        ),
        migrations.AlterField(
            model_name='application',
            name='expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wydatek'),
        ),
        migrations.AlterField(
            model_name='application',
            name='information',
            field=models.TextField(default='', null=True, verbose_name='Informacje'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Przedmiot porozumienia'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota'),
        ),
    ]
