# Generated by Django 4.1 on 2023-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_application_slug_alter_application_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_agreement',
            field=models.DateField(blank=True, null=True, verbose_name='Data porozumienia'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_return',
            field=models.DateField(blank=True, null=True, verbose_name='Data zwrotu'),
        ),
        migrations.AlterField(
            model_name='application',
            name='no_application',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr. wniosku'),
        ),
    ]
