# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_application_settlement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['date_receipt'], 'verbose_name': 'Wniosek', 'verbose_name_plural': 'D.01 - Wnioski'},
        ),
        migrations.AlterModelOptions(
            name='typedonation',
            options={'verbose_name': 'Rodzaj darowizny', 'verbose_name_plural': 'D.02 - Rodzaje darowizn'},
        ),
        migrations.AlterModelOptions(
            name='typefinancialresources',
            options={'verbose_name': 'Rodzaj środków', 'verbose_name_plural': 'D.03 - Rodzaje środków'},
        ),
    ]
