# Generated by Django 4.0.5 on 2022-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_application_engagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='information',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Informacje'),
        ),
    ]
