# Generated by Django 4.0.5 on 2022-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_application_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='change',
            field=models.DateTimeField(auto_now=True, verbose_name='Data zmian'),
        ),
    ]
