# Generated by Django 4.0.5 on 2022-07-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_application_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenditure',
        ),
    ]
