# Generated by Django 4.0.5 on 2022-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_remove_application_engagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='no_agreement',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nr. porozumienia'),
        ),
    ]
