# Generated by Django 4.0.5 on 2022-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_application_no_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
