# Generated by Django 4.0.5 on 2022-07-11 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('content', models.TextField(verbose_name='Treść')),
                ('scan', models.FileField(upload_to=main.models.upload_scan, verbose_name='Skan polecenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Data zmian')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Polecenie',
                'verbose_name_plural': 'Polecenia',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50, verbose_name='Brażna')),
            ],
            options={
                'verbose_name': 'Branża',
                'verbose_name_plural': 'Branże',
            },
        ),
        migrations.CreateModel(
            name='OrganisationTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_book', models.FileField(null=True, upload_to='KWP_telephone/%Y/', verbose_name='Spis telefonów KWP w Poznaniu')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Książka telefoniczna KWP w Poznaniu',
                'verbose_name_plural': 'Książka telefoniczna KWP w Poznaniu',
            },
        ),
        migrations.CreateModel(
            name='SecretariatTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Nr. kierunkowy')),
                ('fax_number', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Nr. faxu')),
                ('secretariat_number', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Nr. do sekretariatu')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Informacje')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Telefon do sekretariatu',
                'verbose_name_plural': 'Telefony do sekretariatu',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=0, null=True, verbose_name='Priorytet')),
                ('team', models.CharField(max_length=50, verbose_name='Komórka Wydziału')),
                ('active', models.BooleanField(verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Komórka Wydziału',
                'verbose_name_plural': 'Komórki Wydziału',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=25, verbose_name='Nazwisko')),
                ('position', models.CharField(blank=True, default='', max_length=20, verbose_name='Stanowisko')),
                ('industry_specialist', models.BooleanField(default=0, verbose_name='Branżysta merytoryczny')),
                ('no_room', models.CharField(blank=True, default='', max_length=2, verbose_name='Nr. pokoju')),
                ('no_tel_room', models.CharField(blank=True, default='', max_length=6, verbose_name='Nr. telefonu')),
                ('no_tel_private', models.CharField(blank=True, default='', max_length=9, verbose_name='Nr. komórkowy')),
                ('information', models.TextField(blank=True, max_length=200, null=True, verbose_name='Informacje')),
                ('deleted', models.BooleanField(default=False, verbose_name='Usunięty')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Data zmian')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='main.industrytype', verbose_name='Branża')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='main.team', verbose_name='Zespół')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
                'ordering': ['team', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zok_team', models.BooleanField(default=False, verbose_name='Ewidencja: Zespoł Obsługi Kancelarynej')),
                ('teams', models.BooleanField(default=False, verbose_name='ZOK - Zespoły')),
                ('commands', models.BooleanField(default=False, verbose_name='ZOK - Polecenia')),
                ('employers', models.BooleanField(default=False, verbose_name='ZOK - Pracownicy')),
                ('zriwt_team', models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Rozliczeń i Wsparcia Technicznego')),
                ('contractors_module', models.BooleanField(default=False, verbose_name='ZRiWT - Kontrahenci - Podgląd')),
                ('contractors_module_edit', models.BooleanField(default=False, verbose_name='ZRiWT - Kontrahenci - Edycja')),
                ('invoices_module', models.BooleanField(default=False, verbose_name='ZRiWT - Faktury - Podgląd')),
                ('invoices_module_edit', models.BooleanField(default=False, verbose_name='ZRiWT - Faktury - Edycja')),
                ('donations_module', models.BooleanField(default=False, verbose_name='ZRiWT - Darowizny - Podgląd')),
                ('donations_module_edit', models.BooleanField(default=False, verbose_name='ZRiWT - Darowizny - Edycja')),
                ('contracts_auction_module', models.BooleanField(default=False, verbose_name='ZRiWT - Umowy ZZP - Podgląd')),
                ('contracts_auction_module_edit', models.BooleanField(default=False, verbose_name='ZRiWT - Umowy ZZP - Edycja')),
                ('investments_module', models.BooleanField(default=False, verbose_name='ZRiWT - Inwestycje - Podgląd')),
                ('investments_module_edit', models.BooleanField(default=False, verbose_name='ZRiWT - Inwestycje - Edycja')),
                ('cpvdict_module', models.BooleanField(default=False, verbose_name='ZRiWT - Rodzajowość - Podgląd')),
                ('cpvdict_module_edit', models.BooleanField(default=False, verbose_name='ZRiWT - Rodzajowość - Edycja')),
                ('gallery_module', models.BooleanField(default=False, verbose_name='ZRiWT - Galeria - Podgląd')),
                ('gallery_module_edit', models.BooleanField(default=False, verbose_name='ZRiWT - Galeria - Edycja')),
                ('zm_team', models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Mieszkaniowy')),
                ('official_flat', models.BooleanField(default=False, verbose_name='ZM - Mieszkania służbowe - Podgląd')),
                ('official_flat_edit', models.BooleanField(default=False, verbose_name='ZM - Mieszkania służbowe - Edycja')),
                ('zn_team', models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Nieruchomości')),
                ('contract_immovables', models.BooleanField(default=False, verbose_name='ZN - Umowy nieruchomości - Podgląd')),
                ('contract_immovables_edit', models.BooleanField(default=False, verbose_name='ZN - Umowy nieruchomości - Edycja')),
                ('ze_team', models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Eksploatacji')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessmodule', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dostęp do modułów',
                'verbose_name_plural': 'Dostęp do modułów',
            },
        ),
    ]
