# Generated by Django 3.2.9 on 2022-04-14 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50, verbose_name='Brażna')),
            ],
            options={
                'verbose_name': 'Branża',
                'verbose_name_plural': 'Branże inspektorów',
            },
        ),
        migrations.CreateModel(
            name='OrganisationTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_book', models.FileField(null=True, upload_to='KWP_telephone/%Y/', verbose_name='Spis telefonów KWP w Poznaniu')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Książka telefoniczna KWP w Poznaniu',
                'verbose_name_plural': 'Książka telefoniczna KWP w Poznaniu',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Komórka Wydziału',
                'verbose_name_plural': 'Komórki Wydziału',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='', max_length=20, verbose_name='Stanowisko')),
                ('fname', models.CharField(blank=True, default='', max_length=15, verbose_name='Imię')),
                ('lname', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Nazwisko')),
                ('numbroom', models.CharField(blank=True, default='', max_length=2, verbose_name='Nr. pokoju')),
                ('numbtelbus', models.CharField(blank=True, default='', max_length=6, verbose_name='Nr. telefonu')),
                ('numbtelpri', models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Nr. komórkowy')),
                ('information', models.CharField(blank=True, max_length=200, null=True, verbose_name='Informacje')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'verbose_name': 'Telefony',
                'verbose_name_plural': 'Telefony',
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=25, verbose_name='Nazwisko')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Zespół')),
            ],
            options={
                'verbose_name': 'Inspektor',
                'verbose_name_plural': 'Inspektorzy',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
