# Generated by Django 3.2.9 on 2022-04-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telephone',
            options={'ordering': ['team', 'position'], 'verbose_name': 'Telefony', 'verbose_name_plural': 'Telefony'},
        ),
        migrations.RenameField(
            model_name='telephone',
            old_name='numbroom',
            new_name='no_room',
        ),
        migrations.RenameField(
            model_name='telephone',
            old_name='numbtelpri',
            new_name='no_tel_private',
        ),
        migrations.RenameField(
            model_name='telephone',
            old_name='numbtelbus',
            new_name='no_tel_room',
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(max_length=50, verbose_name='Zespół'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Zespół'),
        ),
    ]
