# Generated by Django 4.0.5 on 2022-07-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='units',
            field=models.BooleanField(default=False, verbose_name='ZN - Jednostki - Podgląd'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='units_edit',
            field=models.BooleanField(default=False, verbose_name='ZN - Jednostki - Edycja'),
        ),
    ]
