# Generated by Django 4.0.5 on 2022-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='contractors_module_edit',
            field=models.BooleanField(default=False, verbose_name='Kontrahenci - Edycja'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='contracts_immovables_module_edit',
            field=models.BooleanField(default=False, verbose_name='Umowy Najmu - Edycja'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='cpvdict_module_edit',
            field=models.BooleanField(default=False, verbose_name='Rodzajowość - Edycja'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='investments_module_edit',
            field=models.BooleanField(default=False, verbose_name='Inwestycje - Edycja'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='invoices_module_edit',
            field=models.BooleanField(default=False, verbose_name='Faktury - Edycja'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='listregister_float_team_module_edit',
            field=models.BooleanField(default=False, verbose_name='Ewidencja: ZM - Edycja'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='contractors_module',
            field=models.BooleanField(default=False, verbose_name='Kontrahenci - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='contracts_immovables_module',
            field=models.BooleanField(default=False, verbose_name='Umowy Najmu - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='cpvdict_module',
            field=models.BooleanField(default=False, verbose_name='Rodzajowość - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='investments_module',
            field=models.BooleanField(default=False, verbose_name='Inwestycje - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='invoices_module',
            field=models.BooleanField(default=False, verbose_name='Faktury - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='listregister_exploatation_team_module',
            field=models.BooleanField(default=False, verbose_name='Ewidencja: ZE - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='listregister_float_team_module',
            field=models.BooleanField(default=False, verbose_name='Ewidencja: ZM - Podgląd'),
        ),
    ]
