# Generated by Django 3.2.9 on 2021-12-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tele',
            name='team',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
