# Generated by Django 3.2.9 on 2022-04-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20220418_0955'),
        ('main', '0002_auto_20220414_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.AddField(
            model_name='employer',
            name='last_name',
            field=models.CharField(default=1, max_length=25, verbose_name='Nazwisko'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='Imię'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Zespół'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
    ]
