# Generated by Django 4.0.5 on 2022-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accessmodule_contractors_module_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='contracts_auction_module',
            field=models.BooleanField(default=False, verbose_name='Umowy ZZP - Podgląd'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='contracts_auction_module_edit',
            field=models.BooleanField(default=False, verbose_name='Umowy ZZP - Edycja'),
        ),
    ]
