# Generated by Django 3.2.9 on 2021-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_telephone_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_book', models.FileField(null=True, upload_to='KWP_telephone/%Y/', verbose_name='Spis telefonów KWP w Poznaniu')),
            ],
            options={
                'verbose_name': 'Książka telefoniczna KWP w Poznaniu',
                'verbose_name_plural': 'Książka telefoniczna KWP w Poznaniu',
            },
        ),
    ]
