# Generated by Django 4.1 on 2023-04-07 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_team_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="NecesseryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Nazwa pliku")),
                (
                    "file",
                    models.FileField(
                        upload_to=main.models.upload_file, verbose_name="Plik"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="necessery_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plik",
                "verbose_name_plural": "Niezbędne pliki",
                "ordering": ["create_date"],
            },
        ),
    ]
