# Generated by Django 3.2.9 on 2022-01-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inspector_permissionstype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionsType',
            new_name='IndustryType',
        ),
        migrations.RenameField(
            model_name='industrytype',
            old_name='permission',
            new_name='industry',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='permissions',
        ),
        migrations.AddField(
            model_name='inspector',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to='main.industrytype', verbose_name='Branża'),
            preserve_default=False,
        ),
    ]
