# Generated by Django 4.0.5 on 2022-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accessmodule_contract_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='invoices_issues',
            field=models.BooleanField(default=0, verbose_name='Wystawia faktury'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry_specialist',
            field=models.BooleanField(default=0, verbose_name='Branżysta'),
        ),
    ]
