# Generated by Django 3.2.9 on 2021-12-25 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_organisationtelephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationtelephone',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data dodania'),
            preserve_default=False,
        ),
    ]
