# Generated by Django 3.2.9 on 2021-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_tele_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='fname',
            field=models.CharField(max_length=15, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='lname',
            field=models.CharField(max_length=15, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='numbtelbus',
            field=models.CharField(max_length=6, verbose_name='Nr. telefonu'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='numbtelpri',
            field=models.CharField(max_length=9, null=True, verbose_name='Nr. komórkowy'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='position',
            field=models.CharField(max_length=20, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='team',
            field=models.CharField(max_length=50, verbose_name='Zespół'),
        ),
    ]
