# Generated by Django 4.0.5 on 2022-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accessmodule_contracts_auction_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='agllery_module',
            field=models.BooleanField(default=False, verbose_name='Galeria - Podgląd'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='agllery_module_edit',
            field=models.BooleanField(default=False, verbose_name='Galeria - Edycja'),
        ),
    ]
