# Generated by Django 3.2.9 on 2022-01-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220113_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrytype',
            options={'verbose_name': 'Branża', 'verbose_name_plural': 'Branże inspektorów'},
        ),
        migrations.AlterField(
            model_name='industrytype',
            name='industry',
            field=models.CharField(max_length=50, verbose_name='Brażna'),
        ),
    ]
