# Generated by Django 4.1 on 2023-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_necesseryfile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="command",
            options={
                "ordering": ["-create_date"],
                "verbose_name": "Polecenie",
                "verbose_name_plural": "S.07 - Polecenia",
            },
        ),
        migrations.AlterField(
            model_name="command",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data dodania"),
        ),
    ]
