# Generated by Django 3.2.9 on 2022-03-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220113_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Zespół'),
            preserve_default=False,
        ),
    ]
