# Generated by Django 3.2.9 on 2022-04-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220418_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['team', 'last_name'], 'verbose_name': 'Pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
    ]
