# Generated by Django 3.2.9 on 2021-12-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211203_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telephone',
            options={'verbose_name': 'Telefony', 'verbose_name_plural': 'Telefony'},
        ),
    ]
