# Generated by Django 4.0.5 on 2022-06-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_accessmodule_agllery_module_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessmodule',
            old_name='agllery_module',
            new_name='gllery_module',
        ),
        migrations.RenameField(
            model_name='accessmodule',
            old_name='agllery_module_edit',
            new_name='gllery_module_edit',
        ),
    ]
