# Generated by Django 4.1 on 2023-08-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_command_options_alter_command_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='necesseryfile',
            options={'ordering': ['-create_date'], 'verbose_name': 'Plik', 'verbose_name_plural': 'S.09 - Pliki do pobrania'},
        ),
    ]
