# Generated by Django 3.2.9 on 2021-12-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_telephone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Komórka Wydziału',
                'verbose_name_plural': 'Komórki Wydziału',
            },
        ),
        migrations.AlterField(
            model_name='telephone',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
