# Generated by Django 4.0.5 on 2022-07-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employer_invoices_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='id_swop',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='ID SWOP'),
        ),
    ]
