# Generated by Django 4.0.5 on 2022-06-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_agllery_module_accessmodule_gllery_module_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessmodule',
            old_name='gllery_module',
            new_name='gallery_module',
        ),
        migrations.RenameField(
            model_name='accessmodule',
            old_name='gllery_module_edit',
            new_name='gallery_module_edit',
        ),
    ]
