# Generated by Django 3.2.9 on 2021-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211204_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='fname',
            field=models.CharField(blank=True, max_length=15, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='lname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='numbtelbus',
            field=models.CharField(blank=True, max_length=6, verbose_name='Nr. telefonu'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='numbtelpri',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Nr. komórkowy'),
        ),
    ]
