# Generated by Django 4.0.5 on 2022-07-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employer_id_swop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='id_swop',
            field=models.CharField(max_length=6, unique=True, verbose_name='ID SWOP'),
        ),
    ]
