# Generated by Django 3.2.9 on 2022-03-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_employer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractors_profile', models.BooleanField(verbose_name='Moduł kontrahenci')),
                ('invoices_profile', models.BooleanField(verbose_name='Moduł faktury')),
                ('contracts_profile', models.BooleanField(verbose_name='Moduł umowy')),
                ('investments_profile', models.BooleanField(verbose_name='Moduł inwestycje')),
                ('cpvdict_profile', models.BooleanField(verbose_name='Moduł rodzajowość')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
