# Generated by Django 4.1 on 2022-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_employer_id_swop"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessmodule",
            name="buildings_module",
            field=models.BooleanField(
                default=False, verbose_name="ZRiWT - Środki trwałe - budynki - Podgląd"
            ),
        ),
        migrations.AddField(
            model_name="accessmodule",
            name="buildings_module_edit",
            field=models.BooleanField(
                default=False, verbose_name="ZRiWT - Środki trwałe - budynki - Edycja"
            ),
        ),
    ]
