# Generated by Django 4.0.5 on 2022-06-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_accessmodule_contracts_immovables_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessmodule',
            name='contracts_immovables_module',
        ),
        migrations.RemoveField(
            model_name='accessmodule',
            name='contracts_immovables_module_edit',
        ),
        migrations.RemoveField(
            model_name='accessmodule',
            name='listregister_exploatation_team_module',
        ),
        migrations.RemoveField(
            model_name='accessmodule',
            name='listregister_float_team_module',
        ),
        migrations.RemoveField(
            model_name='accessmodule',
            name='listregister_float_team_module_edit',
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='ze_team_module',
            field=models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Eksploatacji'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='zm_team_module',
            field=models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Mieszkaniowy'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='zn_team_module',
            field=models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Nieruchomości'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='zriwt_team_module',
            field=models.BooleanField(default=False, verbose_name='Ewidencja: Zespół Rozliczeń i Wsparcia Technicznego'),
        ),
    ]
