# Generated by Django 4.1 on 2022-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_accessmodule_buildings_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessmodule",
            name="inspections_module",
            field=models.BooleanField(
                default=False, verbose_name="ZRiWT - Przeglądy - Podgląd"
            ),
        ),
        migrations.AddField(
            model_name="accessmodule",
            name="inspections_module_edit",
            field=models.BooleanField(
                default=False, verbose_name="ZRiWT - Przeglądy - Edycja"
            ),
        ),
    ]
