# Generated by Django 3.2.9 on 2021-12-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211204_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephone',
            name='numbroom',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Nr. pokoju'),
        ),
    ]
