# Generated by Django 4.1 on 2022-12-29 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_accessmodule_inspections_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('target', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Zmiana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('borrower', models.ManyToManyField(related_name='car', to='main.employer', verbose_name='Delegat')),
            ],
            options={
                'verbose_name': 'Samochód sużbowy',
                'verbose_name_plural': 'Polecenia',
                'ordering': ['date'],
            },
        ),
    ]
