# Generated by Django 4.0.5 on 2022-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_accessmodule_contracts_immovables_module_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessmodule',
            old_name='ze_team_module',
            new_name='ze_team',
        ),
        migrations.RenameField(
            model_name='accessmodule',
            old_name='zm_team_module',
            new_name='zm_team',
        ),
        migrations.RenameField(
            model_name='accessmodule',
            old_name='zn_team_module',
            new_name='zn_team',
        ),
        migrations.RenameField(
            model_name='accessmodule',
            old_name='zriwt_team_module',
            new_name='zriwt_team',
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='donations_module',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Darowizny - Podgląd'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='donations_module_edit',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Darowizny - Edycja'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='contractors_module',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Kontrahenci - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='contractors_module_edit',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Kontrahenci - Edycja'),
        ),
    ]
