# Generated by Django 4.1 on 2022-12-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-date'], 'verbose_name': 'Samochód sużbowy', 'verbose_name_plural': 'Samochód służbowy'},
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='cars',
            field=models.BooleanField(default=False, verbose_name='ZOK - Rezerwacja samochodu służbowego'),
        ),
        migrations.AlterField(
            model_name='car',
            name='target',
            field=models.TextField(verbose_name='Cel'),
        ),
    ]
