# Generated by Django 3.2.9 on 2022-05-02 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_accessmodule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessmodule', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
