# Generated by Django 4.0.5 on 2022-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_ze_team_module_accessmodule_ze_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='official_flat',
            field=models.BooleanField(default=False, verbose_name='Mieszkania służbowe - Podgląd'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='official_flat_edit',
            field=models.BooleanField(default=False, verbose_name='Mieszkania służbowe - Edycja'),
        ),
    ]
