# Generated by Django 4.0.5 on 2022-06-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_accessmodule_official_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='contract_immovables',
            field=models.BooleanField(default=False, verbose_name='ZN - Umowy nieruchomości - Podgląd'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='contract_immovables_edit',
            field=models.BooleanField(default=False, verbose_name='ZN - Umowy nieruchomości - Edycja'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='contracts_auction_module',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Umowy ZZP - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='contracts_auction_module_edit',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Umowy ZZP - Edycja'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='invoices_module',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Faktury - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='invoices_module_edit',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Faktury - Edycja'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='official_flat',
            field=models.BooleanField(default=False, verbose_name='ZM - Mieszkania służbowe - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='official_flat_edit',
            field=models.BooleanField(default=False, verbose_name='ZM - Mieszkania służbowe - Edycja'),
        ),
    ]
