# Generated by Django 4.1 on 2022-12-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_car_options_accessmodule_cars_alter_car_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='creation_date',
            new_name='create_date',
        ),
    ]
