# Generated by Django 4.1 on 2023-01-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_creation_date_car_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-rent_date'], 'verbose_name': 'Samochód sużbowy', 'verbose_name_plural': 'Samochód służbowy'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date',
            new_name='rent_date',
        ),
    ]
