# Generated by Django 3.2.9 on 2022-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220502_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='listregister_module',
            field=models.BooleanField(default=False, verbose_name='Moduł Ewidencjae WIiR'),
        ),
    ]
