# Generated by Django 4.1 on 2023-01-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_car_options_rename_date_car_rent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='records_letters',
            field=models.BooleanField(default=False, verbose_name='ZE - Ewidencja Pism - Podgląd'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='records_letters_edit',
            field=models.BooleanField(default=False, verbose_name='ZE - Ewidencja Pism - Edycja'),
        ),
    ]
