# Generated by Django 3.2.9 on 2022-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_accessmodule_listregister_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('content', models.TextField(verbose_name='Treść')),
                ('scan', models.FileField(upload_to='KWP_telephone/%Y-%M/', verbose_name='Skan polecenia')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Polecenie',
                'verbose_name_plural': 'Polecenia',
                'ordering': ['create_date'],
            },
        ),
    ]
