# Generated by Django 4.0.5 on 2022-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_accessmodule_commands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodule',
            name='cpvdict_module',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Rodzajowość - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='cpvdict_module_edit',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Rodzajowość - Edycja'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='gallery_module',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Galeria - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='gallery_module_edit',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Galeria - Edycja'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='investments_module',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Inwestycje - Podgląd'),
        ),
        migrations.AlterField(
            model_name='accessmodule',
            name='investments_module_edit',
            field=models.BooleanField(default=False, verbose_name='ZRiWT - Inwestycje - Edycja'),
        ),
    ]
