# Generated by Django 4.1 on 2023-01-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_car_options_alter_car_target'),
        ('main', '0014_accessmodule_records_letters_and_more'),
    ]

    operations = [
    ]
