# Generated by Django 4.0.5 on 2022-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_accessmodule_cpvdict_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informacje'),
        ),
        migrations.AddField(
            model_name='employer',
            name='no_room',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Nr. pokoju'),
        ),
        migrations.AddField(
            model_name='employer',
            name='no_tel_private',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Nr. komórkowy'),
        ),
        migrations.AddField(
            model_name='employer',
            name='no_tel_room',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Nr. telefonu'),
        ),
        migrations.AddField(
            model_name='employer',
            name='position',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Stanowisko'),
        ),
    ]
