# Generated by Django 4.1 on 2023-01-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_20230127_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-rent_date'], 'verbose_name': 'Samochód sużbowy', 'verbose_name_plural': 'Samochód służbowy'},
        ),
    ]
