# Generated by Django 3.2.9 on 2022-05-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_command_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessmodule',
            name='listregister_module',
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='listregister_exploatation_team_module',
            field=models.BooleanField(default=False, verbose_name='Moduł Ewidencja: ZE'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='listregister_float_team_module',
            field=models.BooleanField(default=False, verbose_name='Moduł Ewidencja: ZM'),
        ),
    ]
