# Generated by Django 4.0.5 on 2022-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_employer_industry_alter_employer_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(max_length=50, verbose_name='Komórka Wydziału'),
        ),
    ]
