# Generated by Django 3.2.9 on 2022-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220506_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodule',
            name='cpvdict_module',
            field=models.BooleanField(default=False, verbose_name='Moduł Rodzajowość'),
        ),
    ]
