# Generated by Django 3.2.9 on 2022-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_accessmodule_cpvdict_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='scan',
            field=models.FileField(upload_to='commands/%Y/%m/', verbose_name='Skan polecenia'),
        ),
    ]
