# Generated by Django 4.0.5 on 2022-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='scan',
            field=models.FileField(upload_to='commands/%Y/', verbose_name='Skan polecenia'),
        ),
    ]
