# Generated by Django 4.0.5 on 2022-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_command_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodule',
            name='commands',
            field=models.BooleanField(default=False, verbose_name='ZOK - Polecenia'),
        ),
    ]
