# Generated by Django 4.0.5 on 2022-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_accessmodule_commands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='no_tel_private',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Nr. komórkowy'),
        ),
    ]
