# Generated by Django 4.0.5 on 2022-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_employer_no_tel_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Aktywny'),
            preserve_default=False,
        ),
    ]
