# Generated by Django 4.0.5 on 2022-07-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_team_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Usunięty'),
        ),
    ]
