# Generated by Django 4.0.5 on 2022-07-03 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_employer_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='change',
            field=models.DateTimeField(auto_now=True, verbose_name='Zmiany'),
        ),
        migrations.AddField(
            model_name='employer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
