# Generated by Django 4.0.5 on 2022-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_employer_author_employer_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='information',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Informacje'),
        ),
    ]
