# Generated by Django 4.0.5 on 2022-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_employer_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=0, verbose_name='Aktywny'),
        ),
    ]
