# Generated by Django 4.0.5 on 2022-07-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_team_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Aktywny'),
        ),
    ]
