# Generated by Django 4.0.5 on 2022-07-05 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_alter_team_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='active',
            field=models.BooleanField(verbose_name='Aktywny'),
        ),
    ]
