# Generated by Django 4.0.5 on 2022-07-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_employer_author_alter_team_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Priorytet'),
        ),
    ]
