# Generated by Django 4.0.5 on 2022-07-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_team_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['priority'], 'verbose_name': 'Komórka Wydziału', 'verbose_name_plural': 'Komórki Wydziału'},
        ),
    ]
