# Generated by Django 4.0.5 on 2022-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_team_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry_specialist',
            field=models.BooleanField(default=0, null=True, verbose_name='Branżysta merytoryczny'),
        ),
    ]
