# Generated by Django 4.0.5 on 2022-07-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_employer_industry_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry_specialist',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Branżysta merytoryczny'),
        ),
    ]
