# Generated by Django 4.0.5 on 2022-07-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_employer_industry_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='main.industrytype', verbose_name='Branża'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry_specialist',
            field=models.BooleanField(default=0, verbose_name='Branżysta merytoryczny'),
        ),
    ]
