# Generated by Django 4.0.5 on 2022-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_employer_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='change',
            field=models.DateTimeField(auto_now=True, verbose_name='Data zmian'),
        ),
    ]
