# Generated by Django 4.0.5 on 2022-07-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_command_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='change',
            field=models.DateTimeField(auto_now=True, verbose_name='Data zmian'),
        ),
    ]
