# Generated by Django 4.0.5 on 2022-07-08 07:30

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_employer_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretariatTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Nr. kierunkowy')),
                ('fax_number', models.IntegerField(verbose_name='Nr. faxu')),
                ('secretariat_number', models.IntegerField(verbose_name='Nr. do sekretariatu')),
            ],
            options={
                'verbose_name': 'Telefon do sekretariatu',
                'verbose_name_plural': 'Telefony do sekretariatu',
            },
        ),
        migrations.AlterField(
            model_name='command',
            name='scan',
            field=models.FileField(upload_to=main.models.upload_scan, verbose_name='Skan polecenia'),
        ),
    ]
