# Generated by Django 4.0.5 on 2022-07-08 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_secretariattelephone_alter_command_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretariattelephone',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
