# Generated by Django 4.0.5 on 2022-07-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_secretariattelephone_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretariattelephone',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
    ]
