# Generated by Django 4.0.5 on 2022-07-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_secretariattelephone_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretariattelephone',
            name='information',
            field=models.TextField(default=1, verbose_name='Informacje'),
            preserve_default=False,
        ),
    ]
