# Generated by Django 4.0.5 on 2022-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_secretariattelephone_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretariattelephone',
            name='fax_number',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Nr. faxu'),
        ),
        migrations.AlterField(
            model_name='secretariattelephone',
            name='secretariat_number',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Nr. do sekretariatu'),
        ),
    ]
