# Generated by Django 4.0.5 on 2022-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_secretariattelephone_fax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretariattelephone',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nr. kierunkowy'),
        ),
        migrations.AlterField(
            model_name='secretariattelephone',
            name='fax_number',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Nr. faxu'),
        ),
        migrations.AlterField(
            model_name='secretariattelephone',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje'),
        ),
        migrations.AlterField(
            model_name='secretariattelephone',
            name='secretariat_number',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Nr. do sekretariatu'),
        ),
    ]
