# Generated by Django 4.0.5 on 2022-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_secretariattelephone_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodule',
            name='employers',
            field=models.BooleanField(default=False, verbose_name='ZOK - Pracownicy'),
        ),
        migrations.AddField(
            model_name='accessmodule',
            name='teams',
            field=models.BooleanField(default=False, verbose_name='ZOK - Zespoły'),
        ),
    ]
