# Generated by Django 4.1 on 2022-08-25 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.SmallIntegerField(unique=True, verbose_name='Liczba porządkowa')),
                ('condition', models.CharField(max_length=30, verbose_name='Stan tehcniczny')),
            ],
            options={
                'verbose_name': 'Stan tehcniczny',
                'verbose_name_plural': 'Rodzaje stanów technicznych',
            },
        ),
        migrations.CreateModel(
            name='PatternInspections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_inventory', models.CharField(max_length=15, unique=True)),
                ('date_protocol', models.DateField(verbose_name='Data protokołu')),
                ('conclusions', models.TextField(verbose_name='Wnioski')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Data zmian')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterninspections', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
