# Generated by Django 4.1 on 2023-02-17 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixedasset', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternInspections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_protocol', models.DateField(verbose_name='Data protokołu')),
                ('conclusions', tinymce.models.HTMLField(verbose_name='Wnioski')),
                ('date_next_inspection', models.DateField(blank=True, null=True, verbose_name='Data kolejnego przeglądu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Data zmian')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['date_protocol'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.SmallIntegerField(unique=True, verbose_name='Liczba porządkowa')),
                ('condition', models.CharField(max_length=30, verbose_name='Klasyfikacja stanu technicznego')),
                ('component_use', models.CharField(max_length=9, verbose_name='Procent zużycia elementu')),
            ],
            options={
                'verbose_name': 'Stan techniczny',
                'verbose_name_plural': 'P.10 - Rodzaje stanów technicznych',
                'ordering': ['ordinal_number'],
            },
        ),
        migrations.CreateModel(
            name='TypeInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_name', models.CharField(max_length=50, verbose_name='Rodzaj przeglądu')),
            ],
            options={
                'verbose_name': 'Rodzaj przeglądu',
                'verbose_name_plural': 'P.09 - Rodzaje przeglądu',
            },
        ),
        migrations.CreateModel(
            name='HeatingBoilerInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przegląd kotła grzewczego',
                'verbose_name_plural': 'P.06 - Przeglądy kotłów grzewczych',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='FireInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przegląd przeciwpożarowy',
                'verbose_name_plural': 'P.08 - Przeglądy przeciwpożarowe',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='ElectricalInspectionOneYear',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przedląd elektryczny - roczny',
                'verbose_name_plural': 'P.03 - Przeglądy elektryczne - roczny',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='ElectricalInspectionFiveYear',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przedląd elektryczny - pięcioletni',
                'verbose_name_plural': 'P.04 - Przeglądy elektryczne - pięcioletni',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='ChimneyInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przegląd komina',
                'verbose_name_plural': 'P.05 - Przeglądy kominów',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='BuildingInspectionOneYear',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przegląd budynku techniczny - roczny',
                'verbose_name_plural': 'P.01 - Przeglądy budynków - roczny',
                'ordering': ['no_inventory__unit__county__swop_id'],
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='BuildingInspectionFiveYear',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przegląd budynku techniczny - pięcioletni',
                'verbose_name_plural': 'P.02 - Przeglądy budynków - pięcioletni',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='AirConditionerInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('inspection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu')),
                ('no_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to='fixedasset.building', verbose_name='Obiekt')),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny')),
            ],
            options={
                'verbose_name': 'Przegląd klimatyzatora',
                'verbose_name_plural': 'P.07 - Przeglądy klimatyzatorów',
            },
            bases=('constructioninspections.patterninspections',),
        ),
    ]
