# Generated by Django 4.1 on 2022-08-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalcondition',
            options={'ordering': ['ordinal_number'], 'verbose_name': 'Stan tehcniczny', 'verbose_name_plural': 'Rodzaje stanów technicznych'},
        ),
    ]
