# Generated by Django 4.1 on 2022-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructioninspections", "0002_alter_technicalcondition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="patterninspections",
            name="date_next_inspection",
            field=models.DateField(
                default="2022-02-02", verbose_name="Data kolejnego przeglądu"
            ),
        ),
    ]
