# Generated by Django 4.1 on 2022-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructioninspections", "0003_patterninspections_date_next_inspection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patterninspections",
            name="date_next_inspection",
            field=models.DateField(verbose_name="Data kolejnego przeglądu"),
        ),
    ]
