# Generated by Django 4.1 on 2022-08-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixedasset", "0006_alter_building_state"),
        (
            "constructioninspections",
            "0004_alter_patterninspections_date_next_inspection",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patterninspections",
            name="no_inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patterninspections",
                to="fixedasset.building",
                verbose_name="Nr. inwentarzowy",
            ),
        ),
    ]
