# Generated by Django 4.1 on 2022-08-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("constructioninspections", "0005_alter_patterninspections_no_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingInspection",
            fields=[
                (
                    "patterninspections_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="constructioninspections.patterninspections",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przedląd budynku tehcniczny",
                "verbose_name_plural": "Przeglądy budynków",
                "ordering": [],
            },
            bases=("constructioninspections.patterninspections",),
        ),
        migrations.CreateModel(
            name="TypeInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_nane",
                    models.CharField(max_length=50, verbose_name="Przegląd"),
                ),
            ],
            options={
                "verbose_name": "Rodzaj przeglądu",
                "verbose_name_plural": "Rodzaje przeglądu",
            },
        ),
    ]
