# Generated by Django 4.1 on 2022-08-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0006_buildinginspection_typeinspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChimneyInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
            ],
            options={
                'verbose_name': 'Przedląd komina',
                'verbose_name_plural': 'Przeglądy kominów',
                'ordering': [],
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.RemoveField(
            model_name='typeinspection',
            name='inspection_nane',
        ),
        migrations.AddField(
            model_name='patterninspections',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patterninspections', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeinspection',
            name='inspection_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
    ]
