# Generated by Django 4.1 on 2022-08-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0007_chimneyinspection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingInspectionOneYear',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
            ],
            options={
                'verbose_name': 'Przedląd budynku tehcniczny - roczny',
                'verbose_name_plural': 'Przeglądy budynków - roczne',
                'ordering': [],
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.RenameModel(
            old_name='BuildingInspection',
            new_name='BuildingInspectionFiveYear',
        ),
        migrations.AlterModelOptions(
            name='buildinginspectionfiveyear',
            options={'ordering': [], 'verbose_name': 'Przedląd budynku tehcniczny - pięcioletni', 'verbose_name_plural': 'Przeglądy budynków - pięcioletni'},
        ),
    ]
