# Generated by Django 4.1 on 2022-08-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixedasset', '0007_alter_building_options'),
        ('constructioninspections', '0008_buildinginspectiononeyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninspections',
            name='no_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterninspections', to='fixedasset.building', verbose_name='Obiekt'),
        ),
    ]
