# Generated by Django 4.1 on 2022-08-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0009_alter_patterninspections_no_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditionerInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
            ],
            options={
                'verbose_name': 'Przedląd klimatyzatora',
                'verbose_name_plural': 'Przeglądy klimatyzatorów',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='ElectricalInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
            ],
            options={
                'verbose_name': 'Przedląd elektryczny',
                'verbose_name_plural': 'Przeglądy elektryczne',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='FireInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
            ],
            options={
                'verbose_name': 'Przedląd przeciwpożarowy',
                'verbose_name_plural': 'Przeglądy przeciwpożarowe',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.CreateModel(
            name='HeatingBoilerInspection',
            fields=[
                ('patterninspections_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constructioninspections.patterninspections')),
            ],
            options={
                'verbose_name': 'Przedląd kotła grzewczego',
                'verbose_name_plural': 'Przeglądy kotłów grzewczych',
            },
            bases=('constructioninspections.patterninspections',),
        ),
        migrations.AlterModelOptions(
            name='buildinginspectionfiveyear',
            options={'verbose_name': 'Przedląd budynku tehcniczny - pięcioletni', 'verbose_name_plural': 'Przeglądy budynków - pięcioletni'},
        ),
        migrations.AlterModelOptions(
            name='buildinginspectiononeyear',
            options={'verbose_name': 'Przedląd budynku tehcniczny - roczny', 'verbose_name_plural': 'Przeglądy budynków - roczne'},
        ),
        migrations.AlterModelOptions(
            name='chimneyinspection',
            options={'verbose_name': 'Przedląd komina', 'verbose_name_plural': 'Przeglądy kominów'},
        ),
        migrations.AlterModelOptions(
            name='patterninspections',
            options={'ordering': ['date_protocol']},
        ),
    ]
