# Generated by Django 4.1 on 2022-08-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0010_airconditionerinspection_electricalinspection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinginspectiononeyear',
            options={'verbose_name': 'Przedląd budynku tehcniczny - roczny', 'verbose_name_plural': 'Przeglądy budynków - roczny'},
        ),
    ]
