# Generated by Django 4.1 on 2022-09-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0011_alter_buildinginspectiononeyear_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconditionerinspection',
            options={'verbose_name': 'Przegląd klimatyzatora', 'verbose_name_plural': 'Przeglądy klimatyzatorów'},
        ),
        migrations.AlterModelOptions(
            name='buildinginspectionfiveyear',
            options={'verbose_name': 'Przegląd budynku techniczny - pięcioletni', 'verbose_name_plural': 'Przeglądy budynków - pięcioletni'},
        ),
        migrations.AlterModelOptions(
            name='buildinginspectiononeyear',
            options={'verbose_name': 'Przegląd budynku techniczny - roczny', 'verbose_name_plural': 'Przeglądy budynków - roczny'},
        ),
        migrations.AlterModelOptions(
            name='chimneyinspection',
            options={'verbose_name': 'Przegląd komina', 'verbose_name_plural': 'Przeglądy kominów'},
        ),
        migrations.AlterModelOptions(
            name='fireinspection',
            options={'verbose_name': 'Przegląd przeciwpożarowy', 'verbose_name_plural': 'Przeglądy przeciwpożarowe'},
        ),
        migrations.AlterModelOptions(
            name='heatingboilerinspection',
            options={'verbose_name': 'Przegląd kotła grzewczego', 'verbose_name_plural': 'Przeglądy kotłów grzewczych'},
        ),
        migrations.RemoveField(
            model_name='patterninspections',
            name='inspection_name',
        ),
        migrations.AddField(
            model_name='airconditionerinspection',
            name='inspection_name',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='AirConditionerInspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
        migrations.AddField(
            model_name='buildinginspectionfiveyear',
            name='inspection_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='BuildingInspectionFiveYear', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
        migrations.AddField(
            model_name='buildinginspectiononeyear',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BuildingInspectionOneYear', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
        migrations.AddField(
            model_name='chimneyinspection',
            name='inspection_name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ChimneyInspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
        migrations.AddField(
            model_name='electricalinspection',
            name='inspection_name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ElectricalInspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
        migrations.AddField(
            model_name='fireinspection',
            name='inspection_name',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='FireInspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
        migrations.AddField(
            model_name='heatingboilerinspection',
            name='inspection_name',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='HeatingBoilerInspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
    ]
