# Generated by Django 4.1 on 2022-09-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0012_alter_airconditionerinspection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinginspectiononeyear',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buildinginspectiononeyear', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
        ),
    ]
