# Generated by Django 4.1 on 2022-09-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0013_alter_buildinginspectiononeyear_inspection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconditionerinspection',
            name='inspection_name',
        ),
        migrations.RemoveField(
            model_name='buildinginspectionfiveyear',
            name='inspection_name',
        ),
        migrations.RemoveField(
            model_name='buildinginspectiononeyear',
            name='inspection_name',
        ),
        migrations.RemoveField(
            model_name='chimneyinspection',
            name='inspection_name',
        ),
        migrations.RemoveField(
            model_name='electricalinspection',
            name='inspection_name',
        ),
        migrations.RemoveField(
            model_name='fireinspection',
            name='inspection_name',
        ),
        migrations.RemoveField(
            model_name='heatingboilerinspection',
            name='inspection_name',
        ),
        migrations.AddField(
            model_name='patterninspections',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patterninspections', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
    ]
