# Generated by Django 4.1 on 2022-09-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0014_remove_airconditionerinspection_inspection_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalcondition',
            options={'ordering': ['ordinal_number'], 'verbose_name': 'Stan techniczny', 'verbose_name_plural': 'Rodzaje stanów technicznych'},
        ),
        migrations.AlterField(
            model_name='technicalcondition',
            name='condition',
            field=models.CharField(max_length=30, verbose_name='Stan techniczny'),
        ),
    ]
