# Generated by Django 4.1 on 2022-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0016_electricalinspectiononeyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninspections',
            name='date_next_inspection',
            field=models.DateField(blank=True, null=True, verbose_name='Data kolejnego przeglądu'),
        ),
    ]
