# Generated by Django 4.1 on 2022-10-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0017_alter_patterninspections_date_next_inspection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinginspectiononeyear',
            options={'ordering': ['no_inventory__unit__county__swop_id'], 'verbose_name': 'Przegląd budynku techniczny - roczny', 'verbose_name_plural': 'Przeglądy budynków - roczny'},
        ),
    ]
