# Generated by Django 4.1 on 2022-11-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0018_alter_buildinginspectiononeyear_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalcondition',
            name='component_use',
            field=models.IntegerField(default=1, verbose_name='Procent zużycia elementu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicalcondition',
            name='condition',
            field=models.CharField(max_length=30, verbose_name='Klasyfikacja stanu technicznego'),
        ),
    ]
