# Generated by Django 4.1 on 2022-11-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0020_alter_technicalcondition_component_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterninspections',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patterninspections', to='constructioninspections.technicalcondition'),
            preserve_default=False,
        ),
    ]
