# Generated by Django 4.1 on 2022-11-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0021_patterninspections_technical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninspections',
            name='technical_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterninspections', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
        ),
    ]
