# Generated by Django 4.1 on 2022-11-09 12:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0022_alter_patterninspections_technical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninspections',
            name='conclusions',
            field=tinymce.models.HTMLField(verbose_name='Wnioski'),
        ),
    ]
