# Generated by Django 4.1 on 2022-11-15 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixedasset', '0007_alter_building_options'),
        ('constructioninspections', '0024_alter_patterninspections_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patterninspections',
            name='author',
        ),
        migrations.RemoveField(
            model_name='patterninspections',
            name='inspection_name',
        ),
        migrations.RemoveField(
            model_name='patterninspections',
            name='no_inventory',
        ),
        migrations.RemoveField(
            model_name='patterninspections',
            name='technical_condition',
        ),
        migrations.AddField(
            model_name='airconditionerinspection',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airconditionerinspection',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airconditionerinspection',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airconditionerinspection',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectionfiveyear',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectionfiveyear',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectionfiveyear',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectionfiveyear',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_five_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectiononeyear',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectiononeyear',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectiononeyear',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildinginspectiononeyear',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_inspection_one_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chimneyinspection',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chimneyinspection',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chimneyinspection',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chimneyinspection',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chimney_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectionfiveyear',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectionfiveyear',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectionfiveyear',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectionfiveyear',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_five_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectiononeyear',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectiononeyear',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectiononeyear',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalinspectiononeyear',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection_one_year', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fireinspection',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fireinspection',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fireinspection',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fireinspection',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fire_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heatingboilerinspection',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heatingboilerinspection',
            name='inspection_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to='constructioninspections.typeinspection', verbose_name='Rodzaj przeglądu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heatingboilerinspection',
            name='no_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to='fixedasset.building', verbose_name='Obiekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heatingboilerinspection',
            name='technical_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heating_boiler_inspection', to='constructioninspections.technicalcondition', verbose_name='Stan techniczny'),
            preserve_default=False,
        ),
    ]
