# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructioninspections', '0025_remove_patterninspections_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconditionerinspection',
            options={'verbose_name': 'Przegląd klimatyzatora', 'verbose_name_plural': 'P.07 - Przeglądy klimatyzatorów'},
        ),
        migrations.AlterModelOptions(
            name='buildinginspectionfiveyear',
            options={'verbose_name': 'Przegląd budynku techniczny - pięcioletni', 'verbose_name_plural': 'P.02 - Przeglądy budynków - pięcioletni'},
        ),
        migrations.AlterModelOptions(
            name='buildinginspectiononeyear',
            options={'ordering': ['no_inventory__unit__county__swop_id'], 'verbose_name': 'Przegląd budynku techniczny - roczny', 'verbose_name_plural': 'P.01 - Przeglądy budynków - roczny'},
        ),
        migrations.AlterModelOptions(
            name='chimneyinspection',
            options={'verbose_name': 'Przegląd komina', 'verbose_name_plural': 'P.05 - Przeglądy kominów'},
        ),
        migrations.AlterModelOptions(
            name='electricalinspectionfiveyear',
            options={'verbose_name': 'Przedląd elektryczny - pięcioletni', 'verbose_name_plural': 'P.04 - Przeglądy elektryczne - pięcioletni'},
        ),
        migrations.AlterModelOptions(
            name='electricalinspectiononeyear',
            options={'verbose_name': 'Przedląd elektryczny - roczny', 'verbose_name_plural': 'P.03 - Przeglądy elektryczne - roczny'},
        ),
        migrations.AlterModelOptions(
            name='fireinspection',
            options={'verbose_name': 'Przegląd przeciwpożarowy', 'verbose_name_plural': 'P.08 - Przeglądy przeciwpożarowe'},
        ),
        migrations.AlterModelOptions(
            name='heatingboilerinspection',
            options={'verbose_name': 'Przegląd kotła grzewczego', 'verbose_name_plural': 'P.06 - Przeglądy kotłów grzewczych'},
        ),
        migrations.AlterModelOptions(
            name='technicalcondition',
            options={'ordering': ['ordinal_number'], 'verbose_name': 'Stan techniczny', 'verbose_name_plural': 'P.10 - Rodzaje stanów technicznych'},
        ),
        migrations.AlterModelOptions(
            name='typeinspection',
            options={'verbose_name': 'Rodzaj przeglądu', 'verbose_name_plural': 'P.09 - Rodzaje przeglądu'},
        ),
    ]
