# Generated by Django 3.2.9 on 2022-05-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('area', models.FloatField(max_length=5, verbose_name='Powierzchnia')),
                ('room_numbers', models.IntegerField(verbose_name='Ilość pomieszczeń')),
                ('flor', models.IntegerField(verbose_name='Piętro')),
                ('state', models.BooleanField(default=True, verbose_name='Stan')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='Data zmian')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officialflat', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Mieszkanie służbowe',
                'verbose_name_plural': 'Mieszkania słuzbowe',
            },
        ),
    ]
