# Generated by Django 3.2.9 on 2022-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialflat',
            options={'verbose_name': 'Mieszkanie służbowe', 'verbose_name_plural': 'Mieszkania służbowe'},
        ),
        migrations.AlterField(
            model_name='officialflat',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Powierzchnia'),
        ),
    ]
