# Generated by Django 3.2.9 on 2022-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listregister', '0002_auto_20220506_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialflat',
            name='information',
            field=models.TextField(default=1, verbose_name='Informacje'),
            preserve_default=False,
        ),
    ]
