# Generated by Django 3.2.9 on 2022-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listregister', '0003_officialflat_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialflat',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Powierzchnia'),
        ),
        migrations.AlterField(
            model_name='officialflat',
            name='flor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piętro'),
        ),
        migrations.AlterField(
            model_name='officialflat',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje'),
        ),
        migrations.AlterField(
            model_name='officialflat',
            name='room_numbers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ilość pomieszczeń'),
        ),
    ]
