# Generated by Django 3.2.9 on 2022-05-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listregister', '0005_alter_officialflat_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialflat',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Adres'),
        ),
    ]
