# Generated by Django 3.2.9 on 2022-01-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nocuntractor', models.CharField(max_length=10, unique=True, verbose_name='Nr. kontrahenta')),
                ('nazwa', models.CharField(max_length=30, null=True, verbose_name='Nazwa')),
                ('nip', models.CharField(blank=True, max_length=13, null=True, verbose_name='NIP')),
                ('adres', models.CharField(max_length=30, null=True, verbose_name='Adres')),
                ('kod_pocztowy', models.CharField(max_length=6, null=True, verbose_name='Kod pocztowy')),
                ('miasto', models.CharField(max_length=20, null=True, verbose_name='Miasto')),
                ('informacje', models.TextField(blank=True, default='', null=True, verbose_name='Informacje')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontrahenci',
                'verbose_name_plural': 'Kontrahenci',
                'ordering': ['nazwa'],
            },
        ),
    ]
