# Generated by Django 3.2.9 on 2022-04-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['name'], 'verbose_name': 'Kontrahenci', 'verbose_name_plural': 'Kontrahenci'},
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='adres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='miasto',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='data_utworzenia',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='informacje',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='kod_pocztowy',
            new_name='zip_code',
        ),
    ]
