# Generated by Django 4.1 on 2022-08-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='no_contractor',
            field=models.IntegerField(blank=True, default='', null=True, unique=True, verbose_name='Nr. kontrahenta'),
        ),
    ]
