# Generated by Django 3.2.9 on 2021-12-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contractorbuy',
        ),
    ]
