# Generated by Django 3.2.9 on 2022-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NIP'),
        ),
    ]
