# Generated by Django 3.2.9 on 2021-11-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='utworzenie',
            new_name='data_utworzenia',
        ),
    ]
