# Generated by Django 3.2.9 on 2022-06-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='no_contractor',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Nr. kontrahenta'),
        ),
    ]
