# Generated by Django 4.1 on 2023-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
