# Generated by Django 4.1 on 2023-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_contractor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
