# Generated by Django 3.2.9 on 2021-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_rename_utworzenie_contractor_data_utworzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='informacje',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
