# Generated by Django 3.2.9 on 2022-04-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_auto_20220412_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='nocuntractor',
            new_name='no_contractor',
        ),
    ]
