# Generated by Django 3.2.9 on 2022-05-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_alter_contractor_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='change',
            field=models.DateTimeField(auto_now=True, verbose_name='Zmiany'),
        ),
    ]
