# Generated by Django 3.2.9 on 2021-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_alter_contractorsell_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorbuy',
            name='nocuntractor',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorsell',
            name='nocuntractor',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
