# Generated by Django 3.2.9 on 2021-12-14 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
        ('contractors', '0002_delete_contractorbuy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contractorsell',
            new_name='Contractor',
        ),
    ]
