# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_alter_contractor_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['name'], 'verbose_name': 'Kontrahenci', 'verbose_name_plural': 'K.01 - Kontrahenci'},
        ),
    ]
