# Generated by Django 3.2.9 on 2021-12-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0003_alter_contractor_informacje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractorbuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, null=True)),
                ('nip', models.CharField(max_length=10, null=True, verbose_name='NIP')),
                ('adres', models.CharField(max_length=30, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6, null=True)),
                ('miasto', models.CharField(max_length=20, null=True)),
                ('informacje', models.TextField(blank=True, default='', null=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontrahenci - kupno',
                'verbose_name_plural': 'Kontrahenci - kupno',
            },
        ),
        migrations.CreateModel(
            name='Contractorsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, null=True)),
                ('nip', models.CharField(max_length=10, null=True, verbose_name='NIP')),
                ('adres', models.CharField(max_length=30, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6, null=True)),
                ('miasto', models.CharField(max_length=20, null=True)),
                ('informacje', models.TextField(blank=True, default='', null=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontrahenci - sprzedaż',
                'verbose_name_plural': 'Kontrahenci - sprzedaż',
            },
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
