# Generated by Django 3.2.9 on 2021-12-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_alter_contractorsell_nocuntractor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorsell',
            options={'ordering': ['nazwa'], 'verbose_name': 'Kontrahenci - sprzedaż', 'verbose_name_plural': 'Kontrahenci - sprzedaż'},
        ),
    ]
