# Generated by Django 3.2.9 on 2021-12-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_auto_20211215_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='nip',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='NIP'),
        ),
    ]
