# Generated by Django 3.2.9 on 2022-06-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_alter_contractor_no_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NIP'),
        ),
    ]
