# Generated by Django 4.0.5 on 2022-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_alter_contractor_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa'),
        ),
    ]
