# Generated by Django 4.0.5 on 2022-06-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_alter_contractor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='no_contractor',
            field=models.IntegerField(null=True, unique=True, verbose_name='Nr. kontrahenta'),
        ),
    ]
