# Generated by Django 4.0.5 on 2022-07-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0011_alter_contractor_no_contractor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('no_contractor', 'nip')},
        ),
    ]
