# Generated by Django 4.1 on 2023-03-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedasset', '0002_building_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
