# Generated by Django 4.1 on 2022-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedasset', '0002_alter_building_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Aktualny'),
        ),
    ]
