# Generated by Django 4.1 on 2022-08-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedasset', '0003_building_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindbuilding',
            options={'ordering': ['kind'], 'verbose_name': 'Rodzaj budynku', 'verbose_name_plural': 'Rodzaje budynkuów'},
        ),
        migrations.AlterField(
            model_name='building',
            name='information',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Informacje'),
        ),
    ]
