# Generated by Django 4.1 on 2022-08-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedasset', '0004_alter_kindbuilding_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Stan'),
        ),
    ]
