# Generated by Django 4.1 on 2022-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixedasset', '0005_alter_building_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
    ]
