# Generated by Django 4.1 on 2022-08-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixedasset", "0006_alter_building_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={
                "ordering": ["unit"],
                "verbose_name": "Budynek",
                "verbose_name_plural": "Budynki",
            },
        ),
    ]
