# Generated by Django 4.1 on 2023-02-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixedasset', '0007_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['unit'], 'verbose_name': 'Budynek', 'verbose_name_plural': 'ST.01 - Budynki'},
        ),
        migrations.AlterModelOptions(
            name='kindbuilding',
            options={'ordering': ['kind'], 'verbose_name': 'Rodzaj budynku', 'verbose_name_plural': 'ST.02 - Rodzaje budynkuów'},
        ),
    ]
